// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tee/enclave_outcall.proto

package org.chainmaker.pb.tee;

public final class EnclaveOutcall {
  private EnclaveOutcall() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OutCallGetRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tee.OutCallGetRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string contract_name = 1;</code>
     * @return The contractName.
     */
    java.lang.String getContractName();
    /**
     * <code>string contract_name = 1;</code>
     * @return The bytes for contractName.
     */
    com.google.protobuf.ByteString
        getContractNameBytes();

    /**
     * <code>string key = 2;</code>
     * @return The key.
     */
    java.lang.String getKey();
    /**
     * <code>string key = 2;</code>
     * @return The bytes for key.
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>bytes extra = 3;</code>
     * @return The extra.
     */
    com.google.protobuf.ByteString getExtra();
  }
  /**
   * <pre>
   * out call get
   * </pre>
   *
   * Protobuf type {@code tee.OutCallGetRequest}
   */
  public static final class OutCallGetRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tee.OutCallGetRequest)
      OutCallGetRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OutCallGetRequest.newBuilder() to construct.
    private OutCallGetRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OutCallGetRequest() {
      contractName_ = "";
      key_ = "";
      extra_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new OutCallGetRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OutCallGetRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              contractName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              key_ = s;
              break;
            }
            case 26: {

              extra_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.chainmaker.pb.tee.EnclaveOutcall.internal_static_tee_OutCallGetRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.chainmaker.pb.tee.EnclaveOutcall.internal_static_tee_OutCallGetRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.chainmaker.pb.tee.EnclaveOutcall.OutCallGetRequest.class, org.chainmaker.pb.tee.EnclaveOutcall.OutCallGetRequest.Builder.class);
    }

    public static final int CONTRACT_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object contractName_;
    /**
     * <code>string contract_name = 1;</code>
     * @return The contractName.
     */
    @java.lang.Override
    public java.lang.String getContractName() {
      java.lang.Object ref = contractName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contractName_ = s;
        return s;
      }
    }
    /**
     * <code>string contract_name = 1;</code>
     * @return The bytes for contractName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContractNameBytes() {
      java.lang.Object ref = contractName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contractName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KEY_FIELD_NUMBER = 2;
    private volatile java.lang.Object key_;
    /**
     * <code>string key = 2;</code>
     * @return The key.
     */
    @java.lang.Override
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      }
    }
    /**
     * <code>string key = 2;</code>
     * @return The bytes for key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXTRA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString extra_;
    /**
     * <code>bytes extra = 3;</code>
     * @return The extra.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getExtra() {
      return extra_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(contractName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, contractName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, key_);
      }
      if (!extra_.isEmpty()) {
        output.writeBytes(3, extra_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(contractName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, contractName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, key_);
      }
      if (!extra_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, extra_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.chainmaker.pb.tee.EnclaveOutcall.OutCallGetRequest)) {
        return super.equals(obj);
      }
      org.chainmaker.pb.tee.EnclaveOutcall.OutCallGetRequest other = (org.chainmaker.pb.tee.EnclaveOutcall.OutCallGetRequest) obj;

      if (!getContractName()
          .equals(other.getContractName())) return false;
      if (!getKey()
          .equals(other.getKey())) return false;
      if (!getExtra()
          .equals(other.getExtra())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CONTRACT_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getContractName().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      hash = (37 * hash) + EXTRA_FIELD_NUMBER;
      hash = (53 * hash) + getExtra().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.chainmaker.pb.tee.EnclaveOutcall.OutCallGetRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.chainmaker.pb.tee.EnclaveOutcall.OutCallGetRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.chainmaker.pb.tee.EnclaveOutcall.OutCallGetRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.chainmaker.pb.tee.EnclaveOutcall.OutCallGetRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.chainmaker.pb.tee.EnclaveOutcall.OutCallGetRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.chainmaker.pb.tee.EnclaveOutcall.OutCallGetRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.chainmaker.pb.tee.EnclaveOutcall.OutCallGetRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.chainmaker.pb.tee.EnclaveOutcall.OutCallGetRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.chainmaker.pb.tee.EnclaveOutcall.OutCallGetRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.chainmaker.pb.tee.EnclaveOutcall.OutCallGetRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.chainmaker.pb.tee.EnclaveOutcall.OutCallGetRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.chainmaker.pb.tee.EnclaveOutcall.OutCallGetRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.chainmaker.pb.tee.EnclaveOutcall.OutCallGetRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * out call get
     * </pre>
     *
     * Protobuf type {@code tee.OutCallGetRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tee.OutCallGetRequest)
        org.chainmaker.pb.tee.EnclaveOutcall.OutCallGetRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.chainmaker.pb.tee.EnclaveOutcall.internal_static_tee_OutCallGetRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.chainmaker.pb.tee.EnclaveOutcall.internal_static_tee_OutCallGetRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.chainmaker.pb.tee.EnclaveOutcall.OutCallGetRequest.class, org.chainmaker.pb.tee.EnclaveOutcall.OutCallGetRequest.Builder.class);
      }

      // Construct using org.chainmaker.pb.tee.EnclaveOutcall.OutCallGetRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        contractName_ = "";

        key_ = "";

        extra_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.chainmaker.pb.tee.EnclaveOutcall.internal_static_tee_OutCallGetRequest_descriptor;
      }

      @java.lang.Override
      public org.chainmaker.pb.tee.EnclaveOutcall.OutCallGetRequest getDefaultInstanceForType() {
        return org.chainmaker.pb.tee.EnclaveOutcall.OutCallGetRequest.getDefaultInstance();
      }

      @java.lang.Override
      public org.chainmaker.pb.tee.EnclaveOutcall.OutCallGetRequest build() {
        org.chainmaker.pb.tee.EnclaveOutcall.OutCallGetRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.chainmaker.pb.tee.EnclaveOutcall.OutCallGetRequest buildPartial() {
        org.chainmaker.pb.tee.EnclaveOutcall.OutCallGetRequest result = new org.chainmaker.pb.tee.EnclaveOutcall.OutCallGetRequest(this);
        result.contractName_ = contractName_;
        result.key_ = key_;
        result.extra_ = extra_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.chainmaker.pb.tee.EnclaveOutcall.OutCallGetRequest) {
          return mergeFrom((org.chainmaker.pb.tee.EnclaveOutcall.OutCallGetRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.chainmaker.pb.tee.EnclaveOutcall.OutCallGetRequest other) {
        if (other == org.chainmaker.pb.tee.EnclaveOutcall.OutCallGetRequest.getDefaultInstance()) return this;
        if (!other.getContractName().isEmpty()) {
          contractName_ = other.contractName_;
          onChanged();
        }
        if (!other.getKey().isEmpty()) {
          key_ = other.key_;
          onChanged();
        }
        if (other.getExtra() != com.google.protobuf.ByteString.EMPTY) {
          setExtra(other.getExtra());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.chainmaker.pb.tee.EnclaveOutcall.OutCallGetRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.chainmaker.pb.tee.EnclaveOutcall.OutCallGetRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object contractName_ = "";
      /**
       * <code>string contract_name = 1;</code>
       * @return The contractName.
       */
      public java.lang.String getContractName() {
        java.lang.Object ref = contractName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          contractName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string contract_name = 1;</code>
       * @return The bytes for contractName.
       */
      public com.google.protobuf.ByteString
          getContractNameBytes() {
        java.lang.Object ref = contractName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contractName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string contract_name = 1;</code>
       * @param value The contractName to set.
       * @return This builder for chaining.
       */
      public Builder setContractName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        contractName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string contract_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearContractName() {
        
        contractName_ = getDefaultInstance().getContractName();
        onChanged();
        return this;
      }
      /**
       * <code>string contract_name = 1;</code>
       * @param value The bytes for contractName to set.
       * @return This builder for chaining.
       */
      public Builder setContractNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        contractName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object key_ = "";
      /**
       * <code>string key = 2;</code>
       * @return The key.
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string key = 2;</code>
       * @return The bytes for key.
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string key = 2;</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string key = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>string key = 2;</code>
       * @param value The bytes for key to set.
       * @return This builder for chaining.
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        key_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString extra_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes extra = 3;</code>
       * @return The extra.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getExtra() {
        return extra_;
      }
      /**
       * <code>bytes extra = 3;</code>
       * @param value The extra to set.
       * @return This builder for chaining.
       */
      public Builder setExtra(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        extra_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes extra = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearExtra() {
        
        extra_ = getDefaultInstance().getExtra();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tee.OutCallGetRequest)
    }

    // @@protoc_insertion_point(class_scope:tee.OutCallGetRequest)
    private static final org.chainmaker.pb.tee.EnclaveOutcall.OutCallGetRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.chainmaker.pb.tee.EnclaveOutcall.OutCallGetRequest();
    }

    public static org.chainmaker.pb.tee.EnclaveOutcall.OutCallGetRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OutCallGetRequest>
        PARSER = new com.google.protobuf.AbstractParser<OutCallGetRequest>() {
      @java.lang.Override
      public OutCallGetRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OutCallGetRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OutCallGetRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OutCallGetRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.chainmaker.pb.tee.EnclaveOutcall.OutCallGetRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OutCallPutRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tee.OutCallPutRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string contract_name = 1;</code>
     * @return The contractName.
     */
    java.lang.String getContractName();
    /**
     * <code>string contract_name = 1;</code>
     * @return The bytes for contractName.
     */
    com.google.protobuf.ByteString
        getContractNameBytes();

    /**
     * <code>string key = 2;</code>
     * @return The key.
     */
    java.lang.String getKey();
    /**
     * <code>string key = 2;</code>
     * @return The bytes for key.
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>bytes value = 3;</code>
     * @return The value.
     */
    com.google.protobuf.ByteString getValue();
  }
  /**
   * <pre>
   * out call put
   * </pre>
   *
   * Protobuf type {@code tee.OutCallPutRequest}
   */
  public static final class OutCallPutRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tee.OutCallPutRequest)
      OutCallPutRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OutCallPutRequest.newBuilder() to construct.
    private OutCallPutRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OutCallPutRequest() {
      contractName_ = "";
      key_ = "";
      value_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new OutCallPutRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OutCallPutRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              contractName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              key_ = s;
              break;
            }
            case 26: {

              value_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.chainmaker.pb.tee.EnclaveOutcall.internal_static_tee_OutCallPutRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.chainmaker.pb.tee.EnclaveOutcall.internal_static_tee_OutCallPutRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.chainmaker.pb.tee.EnclaveOutcall.OutCallPutRequest.class, org.chainmaker.pb.tee.EnclaveOutcall.OutCallPutRequest.Builder.class);
    }

    public static final int CONTRACT_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object contractName_;
    /**
     * <code>string contract_name = 1;</code>
     * @return The contractName.
     */
    @java.lang.Override
    public java.lang.String getContractName() {
      java.lang.Object ref = contractName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contractName_ = s;
        return s;
      }
    }
    /**
     * <code>string contract_name = 1;</code>
     * @return The bytes for contractName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContractNameBytes() {
      java.lang.Object ref = contractName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contractName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KEY_FIELD_NUMBER = 2;
    private volatile java.lang.Object key_;
    /**
     * <code>string key = 2;</code>
     * @return The key.
     */
    @java.lang.Override
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      }
    }
    /**
     * <code>string key = 2;</code>
     * @return The bytes for key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString value_;
    /**
     * <code>bytes value = 3;</code>
     * @return The value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(contractName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, contractName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, key_);
      }
      if (!value_.isEmpty()) {
        output.writeBytes(3, value_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(contractName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, contractName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, key_);
      }
      if (!value_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, value_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.chainmaker.pb.tee.EnclaveOutcall.OutCallPutRequest)) {
        return super.equals(obj);
      }
      org.chainmaker.pb.tee.EnclaveOutcall.OutCallPutRequest other = (org.chainmaker.pb.tee.EnclaveOutcall.OutCallPutRequest) obj;

      if (!getContractName()
          .equals(other.getContractName())) return false;
      if (!getKey()
          .equals(other.getKey())) return false;
      if (!getValue()
          .equals(other.getValue())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CONTRACT_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getContractName().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.chainmaker.pb.tee.EnclaveOutcall.OutCallPutRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.chainmaker.pb.tee.EnclaveOutcall.OutCallPutRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.chainmaker.pb.tee.EnclaveOutcall.OutCallPutRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.chainmaker.pb.tee.EnclaveOutcall.OutCallPutRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.chainmaker.pb.tee.EnclaveOutcall.OutCallPutRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.chainmaker.pb.tee.EnclaveOutcall.OutCallPutRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.chainmaker.pb.tee.EnclaveOutcall.OutCallPutRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.chainmaker.pb.tee.EnclaveOutcall.OutCallPutRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.chainmaker.pb.tee.EnclaveOutcall.OutCallPutRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.chainmaker.pb.tee.EnclaveOutcall.OutCallPutRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.chainmaker.pb.tee.EnclaveOutcall.OutCallPutRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.chainmaker.pb.tee.EnclaveOutcall.OutCallPutRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.chainmaker.pb.tee.EnclaveOutcall.OutCallPutRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * out call put
     * </pre>
     *
     * Protobuf type {@code tee.OutCallPutRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tee.OutCallPutRequest)
        org.chainmaker.pb.tee.EnclaveOutcall.OutCallPutRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.chainmaker.pb.tee.EnclaveOutcall.internal_static_tee_OutCallPutRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.chainmaker.pb.tee.EnclaveOutcall.internal_static_tee_OutCallPutRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.chainmaker.pb.tee.EnclaveOutcall.OutCallPutRequest.class, org.chainmaker.pb.tee.EnclaveOutcall.OutCallPutRequest.Builder.class);
      }

      // Construct using org.chainmaker.pb.tee.EnclaveOutcall.OutCallPutRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        contractName_ = "";

        key_ = "";

        value_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.chainmaker.pb.tee.EnclaveOutcall.internal_static_tee_OutCallPutRequest_descriptor;
      }

      @java.lang.Override
      public org.chainmaker.pb.tee.EnclaveOutcall.OutCallPutRequest getDefaultInstanceForType() {
        return org.chainmaker.pb.tee.EnclaveOutcall.OutCallPutRequest.getDefaultInstance();
      }

      @java.lang.Override
      public org.chainmaker.pb.tee.EnclaveOutcall.OutCallPutRequest build() {
        org.chainmaker.pb.tee.EnclaveOutcall.OutCallPutRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.chainmaker.pb.tee.EnclaveOutcall.OutCallPutRequest buildPartial() {
        org.chainmaker.pb.tee.EnclaveOutcall.OutCallPutRequest result = new org.chainmaker.pb.tee.EnclaveOutcall.OutCallPutRequest(this);
        result.contractName_ = contractName_;
        result.key_ = key_;
        result.value_ = value_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.chainmaker.pb.tee.EnclaveOutcall.OutCallPutRequest) {
          return mergeFrom((org.chainmaker.pb.tee.EnclaveOutcall.OutCallPutRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.chainmaker.pb.tee.EnclaveOutcall.OutCallPutRequest other) {
        if (other == org.chainmaker.pb.tee.EnclaveOutcall.OutCallPutRequest.getDefaultInstance()) return this;
        if (!other.getContractName().isEmpty()) {
          contractName_ = other.contractName_;
          onChanged();
        }
        if (!other.getKey().isEmpty()) {
          key_ = other.key_;
          onChanged();
        }
        if (other.getValue() != com.google.protobuf.ByteString.EMPTY) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.chainmaker.pb.tee.EnclaveOutcall.OutCallPutRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.chainmaker.pb.tee.EnclaveOutcall.OutCallPutRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object contractName_ = "";
      /**
       * <code>string contract_name = 1;</code>
       * @return The contractName.
       */
      public java.lang.String getContractName() {
        java.lang.Object ref = contractName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          contractName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string contract_name = 1;</code>
       * @return The bytes for contractName.
       */
      public com.google.protobuf.ByteString
          getContractNameBytes() {
        java.lang.Object ref = contractName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contractName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string contract_name = 1;</code>
       * @param value The contractName to set.
       * @return This builder for chaining.
       */
      public Builder setContractName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        contractName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string contract_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearContractName() {
        
        contractName_ = getDefaultInstance().getContractName();
        onChanged();
        return this;
      }
      /**
       * <code>string contract_name = 1;</code>
       * @param value The bytes for contractName to set.
       * @return This builder for chaining.
       */
      public Builder setContractNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        contractName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object key_ = "";
      /**
       * <code>string key = 2;</code>
       * @return The key.
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string key = 2;</code>
       * @return The bytes for key.
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string key = 2;</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string key = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>string key = 2;</code>
       * @param value The bytes for key to set.
       * @return This builder for chaining.
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        key_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes value = 3;</code>
       * @return The value.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <code>bytes value = 3;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes value = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tee.OutCallPutRequest)
    }

    // @@protoc_insertion_point(class_scope:tee.OutCallPutRequest)
    private static final org.chainmaker.pb.tee.EnclaveOutcall.OutCallPutRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.chainmaker.pb.tee.EnclaveOutcall.OutCallPutRequest();
    }

    public static org.chainmaker.pb.tee.EnclaveOutcall.OutCallPutRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OutCallPutRequest>
        PARSER = new com.google.protobuf.AbstractParser<OutCallPutRequest>() {
      @java.lang.Override
      public OutCallPutRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OutCallPutRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OutCallPutRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OutCallPutRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.chainmaker.pb.tee.EnclaveOutcall.OutCallPutRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tee_OutCallGetRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tee_OutCallGetRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tee_OutCallPutRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tee_OutCallPutRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031tee/enclave_outcall.proto\022\003tee\032\023common" +
      "/result.proto\"F\n\021OutCallGetRequest\022\025\n\rco" +
      "ntract_name\030\001 \001(\t\022\013\n\003key\030\002 \001(\t\022\r\n\005extra\030" +
      "\003 \001(\014\"F\n\021OutCallPutRequest\022\025\n\rcontract_n" +
      "ame\030\001 \001(\t\022\013\n\003key\030\002 \001(\t\022\r\n\005value\030\003 \001(\0142\226\001" +
      "\n\024EnclaveOutCallServer\022>\n\nOutCallGet\022\026.t" +
      "ee.OutCallGetRequest\032\026.common.ContractRe" +
      "sult\"\000\022>\n\nOutCallPut\022\026.tee.OutCallPutReq" +
      "uest\032\026.common.ContractResult\"\000B<\n\025org.ch" +
      "ainmaker.pb.teeZ#chainmaker.org/chainmak" +
      "er/pb-go/teeb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.chainmaker.pb.common.ResultOuterClass.getDescriptor(),
        });
    internal_static_tee_OutCallGetRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tee_OutCallGetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tee_OutCallGetRequest_descriptor,
        new java.lang.String[] { "ContractName", "Key", "Extra", });
    internal_static_tee_OutCallPutRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tee_OutCallPutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tee_OutCallPutRequest_descriptor,
        new java.lang.String[] { "ContractName", "Key", "Value", });
    org.chainmaker.pb.common.ResultOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
