// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: discovery/discovery.proto

package org.chainmaker.pb.discovery;

public final class Discovery {
  private Discovery() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChainInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:discovery.ChainInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * block height
     * </pre>
     *
     * <code>uint64 block_height = 1;</code>
     * @return The blockHeight.
     */
    long getBlockHeight();

    /**
     * <pre>
     * node list
     * </pre>
     *
     * <code>repeated .discovery.Node node_list = 2;</code>
     */
    java.util.List<org.chainmaker.pb.discovery.Discovery.Node> 
        getNodeListList();
    /**
     * <pre>
     * node list
     * </pre>
     *
     * <code>repeated .discovery.Node node_list = 2;</code>
     */
    org.chainmaker.pb.discovery.Discovery.Node getNodeList(int index);
    /**
     * <pre>
     * node list
     * </pre>
     *
     * <code>repeated .discovery.Node node_list = 2;</code>
     */
    int getNodeListCount();
    /**
     * <pre>
     * node list
     * </pre>
     *
     * <code>repeated .discovery.Node node_list = 2;</code>
     */
    java.util.List<? extends org.chainmaker.pb.discovery.Discovery.NodeOrBuilder> 
        getNodeListOrBuilderList();
    /**
     * <pre>
     * node list
     * </pre>
     *
     * <code>repeated .discovery.Node node_list = 2;</code>
     */
    org.chainmaker.pb.discovery.Discovery.NodeOrBuilder getNodeListOrBuilder(
        int index);
  }
  /**
   * <pre>
   * information of a blockchain
   * </pre>
   *
   * Protobuf type {@code discovery.ChainInfo}
   */
  public static final class ChainInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:discovery.ChainInfo)
      ChainInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChainInfo.newBuilder() to construct.
    private ChainInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChainInfo() {
      nodeList_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChainInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChainInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              blockHeight_ = input.readUInt64();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                nodeList_ = new java.util.ArrayList<org.chainmaker.pb.discovery.Discovery.Node>();
                mutable_bitField0_ |= 0x00000001;
              }
              nodeList_.add(
                  input.readMessage(org.chainmaker.pb.discovery.Discovery.Node.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          nodeList_ = java.util.Collections.unmodifiableList(nodeList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.chainmaker.pb.discovery.Discovery.internal_static_discovery_ChainInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.chainmaker.pb.discovery.Discovery.internal_static_discovery_ChainInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.chainmaker.pb.discovery.Discovery.ChainInfo.class, org.chainmaker.pb.discovery.Discovery.ChainInfo.Builder.class);
    }

    public static final int BLOCK_HEIGHT_FIELD_NUMBER = 1;
    private long blockHeight_;
    /**
     * <pre>
     * block height
     * </pre>
     *
     * <code>uint64 block_height = 1;</code>
     * @return The blockHeight.
     */
    @java.lang.Override
    public long getBlockHeight() {
      return blockHeight_;
    }

    public static final int NODE_LIST_FIELD_NUMBER = 2;
    private java.util.List<org.chainmaker.pb.discovery.Discovery.Node> nodeList_;
    /**
     * <pre>
     * node list
     * </pre>
     *
     * <code>repeated .discovery.Node node_list = 2;</code>
     */
    @java.lang.Override
    public java.util.List<org.chainmaker.pb.discovery.Discovery.Node> getNodeListList() {
      return nodeList_;
    }
    /**
     * <pre>
     * node list
     * </pre>
     *
     * <code>repeated .discovery.Node node_list = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.chainmaker.pb.discovery.Discovery.NodeOrBuilder> 
        getNodeListOrBuilderList() {
      return nodeList_;
    }
    /**
     * <pre>
     * node list
     * </pre>
     *
     * <code>repeated .discovery.Node node_list = 2;</code>
     */
    @java.lang.Override
    public int getNodeListCount() {
      return nodeList_.size();
    }
    /**
     * <pre>
     * node list
     * </pre>
     *
     * <code>repeated .discovery.Node node_list = 2;</code>
     */
    @java.lang.Override
    public org.chainmaker.pb.discovery.Discovery.Node getNodeList(int index) {
      return nodeList_.get(index);
    }
    /**
     * <pre>
     * node list
     * </pre>
     *
     * <code>repeated .discovery.Node node_list = 2;</code>
     */
    @java.lang.Override
    public org.chainmaker.pb.discovery.Discovery.NodeOrBuilder getNodeListOrBuilder(
        int index) {
      return nodeList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (blockHeight_ != 0L) {
        output.writeUInt64(1, blockHeight_);
      }
      for (int i = 0; i < nodeList_.size(); i++) {
        output.writeMessage(2, nodeList_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (blockHeight_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, blockHeight_);
      }
      for (int i = 0; i < nodeList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, nodeList_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.chainmaker.pb.discovery.Discovery.ChainInfo)) {
        return super.equals(obj);
      }
      org.chainmaker.pb.discovery.Discovery.ChainInfo other = (org.chainmaker.pb.discovery.Discovery.ChainInfo) obj;

      if (getBlockHeight()
          != other.getBlockHeight()) return false;
      if (!getNodeListList()
          .equals(other.getNodeListList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BLOCK_HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBlockHeight());
      if (getNodeListCount() > 0) {
        hash = (37 * hash) + NODE_LIST_FIELD_NUMBER;
        hash = (53 * hash) + getNodeListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.chainmaker.pb.discovery.Discovery.ChainInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.chainmaker.pb.discovery.Discovery.ChainInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.chainmaker.pb.discovery.Discovery.ChainInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.chainmaker.pb.discovery.Discovery.ChainInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.chainmaker.pb.discovery.Discovery.ChainInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.chainmaker.pb.discovery.Discovery.ChainInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.chainmaker.pb.discovery.Discovery.ChainInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.chainmaker.pb.discovery.Discovery.ChainInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.chainmaker.pb.discovery.Discovery.ChainInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.chainmaker.pb.discovery.Discovery.ChainInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.chainmaker.pb.discovery.Discovery.ChainInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.chainmaker.pb.discovery.Discovery.ChainInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.chainmaker.pb.discovery.Discovery.ChainInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * information of a blockchain
     * </pre>
     *
     * Protobuf type {@code discovery.ChainInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:discovery.ChainInfo)
        org.chainmaker.pb.discovery.Discovery.ChainInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.chainmaker.pb.discovery.Discovery.internal_static_discovery_ChainInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.chainmaker.pb.discovery.Discovery.internal_static_discovery_ChainInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.chainmaker.pb.discovery.Discovery.ChainInfo.class, org.chainmaker.pb.discovery.Discovery.ChainInfo.Builder.class);
      }

      // Construct using org.chainmaker.pb.discovery.Discovery.ChainInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getNodeListFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        blockHeight_ = 0L;

        if (nodeListBuilder_ == null) {
          nodeList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          nodeListBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.chainmaker.pb.discovery.Discovery.internal_static_discovery_ChainInfo_descriptor;
      }

      @java.lang.Override
      public org.chainmaker.pb.discovery.Discovery.ChainInfo getDefaultInstanceForType() {
        return org.chainmaker.pb.discovery.Discovery.ChainInfo.getDefaultInstance();
      }

      @java.lang.Override
      public org.chainmaker.pb.discovery.Discovery.ChainInfo build() {
        org.chainmaker.pb.discovery.Discovery.ChainInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.chainmaker.pb.discovery.Discovery.ChainInfo buildPartial() {
        org.chainmaker.pb.discovery.Discovery.ChainInfo result = new org.chainmaker.pb.discovery.Discovery.ChainInfo(this);
        int from_bitField0_ = bitField0_;
        result.blockHeight_ = blockHeight_;
        if (nodeListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            nodeList_ = java.util.Collections.unmodifiableList(nodeList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.nodeList_ = nodeList_;
        } else {
          result.nodeList_ = nodeListBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.chainmaker.pb.discovery.Discovery.ChainInfo) {
          return mergeFrom((org.chainmaker.pb.discovery.Discovery.ChainInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.chainmaker.pb.discovery.Discovery.ChainInfo other) {
        if (other == org.chainmaker.pb.discovery.Discovery.ChainInfo.getDefaultInstance()) return this;
        if (other.getBlockHeight() != 0L) {
          setBlockHeight(other.getBlockHeight());
        }
        if (nodeListBuilder_ == null) {
          if (!other.nodeList_.isEmpty()) {
            if (nodeList_.isEmpty()) {
              nodeList_ = other.nodeList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureNodeListIsMutable();
              nodeList_.addAll(other.nodeList_);
            }
            onChanged();
          }
        } else {
          if (!other.nodeList_.isEmpty()) {
            if (nodeListBuilder_.isEmpty()) {
              nodeListBuilder_.dispose();
              nodeListBuilder_ = null;
              nodeList_ = other.nodeList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              nodeListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getNodeListFieldBuilder() : null;
            } else {
              nodeListBuilder_.addAllMessages(other.nodeList_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.chainmaker.pb.discovery.Discovery.ChainInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.chainmaker.pb.discovery.Discovery.ChainInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long blockHeight_ ;
      /**
       * <pre>
       * block height
       * </pre>
       *
       * <code>uint64 block_height = 1;</code>
       * @return The blockHeight.
       */
      @java.lang.Override
      public long getBlockHeight() {
        return blockHeight_;
      }
      /**
       * <pre>
       * block height
       * </pre>
       *
       * <code>uint64 block_height = 1;</code>
       * @param value The blockHeight to set.
       * @return This builder for chaining.
       */
      public Builder setBlockHeight(long value) {
        
        blockHeight_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * block height
       * </pre>
       *
       * <code>uint64 block_height = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBlockHeight() {
        
        blockHeight_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<org.chainmaker.pb.discovery.Discovery.Node> nodeList_ =
        java.util.Collections.emptyList();
      private void ensureNodeListIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          nodeList_ = new java.util.ArrayList<org.chainmaker.pb.discovery.Discovery.Node>(nodeList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.chainmaker.pb.discovery.Discovery.Node, org.chainmaker.pb.discovery.Discovery.Node.Builder, org.chainmaker.pb.discovery.Discovery.NodeOrBuilder> nodeListBuilder_;

      /**
       * <pre>
       * node list
       * </pre>
       *
       * <code>repeated .discovery.Node node_list = 2;</code>
       */
      public java.util.List<org.chainmaker.pb.discovery.Discovery.Node> getNodeListList() {
        if (nodeListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(nodeList_);
        } else {
          return nodeListBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * node list
       * </pre>
       *
       * <code>repeated .discovery.Node node_list = 2;</code>
       */
      public int getNodeListCount() {
        if (nodeListBuilder_ == null) {
          return nodeList_.size();
        } else {
          return nodeListBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * node list
       * </pre>
       *
       * <code>repeated .discovery.Node node_list = 2;</code>
       */
      public org.chainmaker.pb.discovery.Discovery.Node getNodeList(int index) {
        if (nodeListBuilder_ == null) {
          return nodeList_.get(index);
        } else {
          return nodeListBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * node list
       * </pre>
       *
       * <code>repeated .discovery.Node node_list = 2;</code>
       */
      public Builder setNodeList(
          int index, org.chainmaker.pb.discovery.Discovery.Node value) {
        if (nodeListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodeListIsMutable();
          nodeList_.set(index, value);
          onChanged();
        } else {
          nodeListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * node list
       * </pre>
       *
       * <code>repeated .discovery.Node node_list = 2;</code>
       */
      public Builder setNodeList(
          int index, org.chainmaker.pb.discovery.Discovery.Node.Builder builderForValue) {
        if (nodeListBuilder_ == null) {
          ensureNodeListIsMutable();
          nodeList_.set(index, builderForValue.build());
          onChanged();
        } else {
          nodeListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * node list
       * </pre>
       *
       * <code>repeated .discovery.Node node_list = 2;</code>
       */
      public Builder addNodeList(org.chainmaker.pb.discovery.Discovery.Node value) {
        if (nodeListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodeListIsMutable();
          nodeList_.add(value);
          onChanged();
        } else {
          nodeListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * node list
       * </pre>
       *
       * <code>repeated .discovery.Node node_list = 2;</code>
       */
      public Builder addNodeList(
          int index, org.chainmaker.pb.discovery.Discovery.Node value) {
        if (nodeListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodeListIsMutable();
          nodeList_.add(index, value);
          onChanged();
        } else {
          nodeListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * node list
       * </pre>
       *
       * <code>repeated .discovery.Node node_list = 2;</code>
       */
      public Builder addNodeList(
          org.chainmaker.pb.discovery.Discovery.Node.Builder builderForValue) {
        if (nodeListBuilder_ == null) {
          ensureNodeListIsMutable();
          nodeList_.add(builderForValue.build());
          onChanged();
        } else {
          nodeListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * node list
       * </pre>
       *
       * <code>repeated .discovery.Node node_list = 2;</code>
       */
      public Builder addNodeList(
          int index, org.chainmaker.pb.discovery.Discovery.Node.Builder builderForValue) {
        if (nodeListBuilder_ == null) {
          ensureNodeListIsMutable();
          nodeList_.add(index, builderForValue.build());
          onChanged();
        } else {
          nodeListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * node list
       * </pre>
       *
       * <code>repeated .discovery.Node node_list = 2;</code>
       */
      public Builder addAllNodeList(
          java.lang.Iterable<? extends org.chainmaker.pb.discovery.Discovery.Node> values) {
        if (nodeListBuilder_ == null) {
          ensureNodeListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, nodeList_);
          onChanged();
        } else {
          nodeListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * node list
       * </pre>
       *
       * <code>repeated .discovery.Node node_list = 2;</code>
       */
      public Builder clearNodeList() {
        if (nodeListBuilder_ == null) {
          nodeList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          nodeListBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * node list
       * </pre>
       *
       * <code>repeated .discovery.Node node_list = 2;</code>
       */
      public Builder removeNodeList(int index) {
        if (nodeListBuilder_ == null) {
          ensureNodeListIsMutable();
          nodeList_.remove(index);
          onChanged();
        } else {
          nodeListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * node list
       * </pre>
       *
       * <code>repeated .discovery.Node node_list = 2;</code>
       */
      public org.chainmaker.pb.discovery.Discovery.Node.Builder getNodeListBuilder(
          int index) {
        return getNodeListFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * node list
       * </pre>
       *
       * <code>repeated .discovery.Node node_list = 2;</code>
       */
      public org.chainmaker.pb.discovery.Discovery.NodeOrBuilder getNodeListOrBuilder(
          int index) {
        if (nodeListBuilder_ == null) {
          return nodeList_.get(index);  } else {
          return nodeListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * node list
       * </pre>
       *
       * <code>repeated .discovery.Node node_list = 2;</code>
       */
      public java.util.List<? extends org.chainmaker.pb.discovery.Discovery.NodeOrBuilder> 
           getNodeListOrBuilderList() {
        if (nodeListBuilder_ != null) {
          return nodeListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(nodeList_);
        }
      }
      /**
       * <pre>
       * node list
       * </pre>
       *
       * <code>repeated .discovery.Node node_list = 2;</code>
       */
      public org.chainmaker.pb.discovery.Discovery.Node.Builder addNodeListBuilder() {
        return getNodeListFieldBuilder().addBuilder(
            org.chainmaker.pb.discovery.Discovery.Node.getDefaultInstance());
      }
      /**
       * <pre>
       * node list
       * </pre>
       *
       * <code>repeated .discovery.Node node_list = 2;</code>
       */
      public org.chainmaker.pb.discovery.Discovery.Node.Builder addNodeListBuilder(
          int index) {
        return getNodeListFieldBuilder().addBuilder(
            index, org.chainmaker.pb.discovery.Discovery.Node.getDefaultInstance());
      }
      /**
       * <pre>
       * node list
       * </pre>
       *
       * <code>repeated .discovery.Node node_list = 2;</code>
       */
      public java.util.List<org.chainmaker.pb.discovery.Discovery.Node.Builder> 
           getNodeListBuilderList() {
        return getNodeListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.chainmaker.pb.discovery.Discovery.Node, org.chainmaker.pb.discovery.Discovery.Node.Builder, org.chainmaker.pb.discovery.Discovery.NodeOrBuilder> 
          getNodeListFieldBuilder() {
        if (nodeListBuilder_ == null) {
          nodeListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.chainmaker.pb.discovery.Discovery.Node, org.chainmaker.pb.discovery.Discovery.Node.Builder, org.chainmaker.pb.discovery.Discovery.NodeOrBuilder>(
                  nodeList_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          nodeList_ = null;
        }
        return nodeListBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:discovery.ChainInfo)
    }

    // @@protoc_insertion_point(class_scope:discovery.ChainInfo)
    private static final org.chainmaker.pb.discovery.Discovery.ChainInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.chainmaker.pb.discovery.Discovery.ChainInfo();
    }

    public static org.chainmaker.pb.discovery.Discovery.ChainInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChainInfo>
        PARSER = new com.google.protobuf.AbstractParser<ChainInfo>() {
      @java.lang.Override
      public ChainInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChainInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChainInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChainInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.chainmaker.pb.discovery.Discovery.ChainInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NodeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:discovery.Node)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * node identifier
     * </pre>
     *
     * <code>string node_id = 1;</code>
     * @return The nodeId.
     */
    java.lang.String getNodeId();
    /**
     * <pre>
     * node identifier
     * </pre>
     *
     * <code>string node_id = 1;</code>
     * @return The bytes for nodeId.
     */
    com.google.protobuf.ByteString
        getNodeIdBytes();

    /**
     * <pre>
     * node address
     * </pre>
     *
     * <code>string node_address = 2;</code>
     * @return The nodeAddress.
     */
    java.lang.String getNodeAddress();
    /**
     * <pre>
     * node address
     * </pre>
     *
     * <code>string node_address = 2;</code>
     * @return The bytes for nodeAddress.
     */
    com.google.protobuf.ByteString
        getNodeAddressBytes();

    /**
     * <pre>
     * TLS certificate of the node
     * </pre>
     *
     * <code>bytes node_tls_cert = 3;</code>
     * @return The nodeTlsCert.
     */
    com.google.protobuf.ByteString getNodeTlsCert();
  }
  /**
   * <pre>
   * information of a blockchain node
   * </pre>
   *
   * Protobuf type {@code discovery.Node}
   */
  public static final class Node extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:discovery.Node)
      NodeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Node.newBuilder() to construct.
    private Node(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Node() {
      nodeId_ = "";
      nodeAddress_ = "";
      nodeTlsCert_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Node();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Node(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              nodeId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              nodeAddress_ = s;
              break;
            }
            case 26: {

              nodeTlsCert_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.chainmaker.pb.discovery.Discovery.internal_static_discovery_Node_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.chainmaker.pb.discovery.Discovery.internal_static_discovery_Node_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.chainmaker.pb.discovery.Discovery.Node.class, org.chainmaker.pb.discovery.Discovery.Node.Builder.class);
    }

    public static final int NODE_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object nodeId_;
    /**
     * <pre>
     * node identifier
     * </pre>
     *
     * <code>string node_id = 1;</code>
     * @return The nodeId.
     */
    @java.lang.Override
    public java.lang.String getNodeId() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nodeId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * node identifier
     * </pre>
     *
     * <code>string node_id = 1;</code>
     * @return The bytes for nodeId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNodeIdBytes() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NODE_ADDRESS_FIELD_NUMBER = 2;
    private volatile java.lang.Object nodeAddress_;
    /**
     * <pre>
     * node address
     * </pre>
     *
     * <code>string node_address = 2;</code>
     * @return The nodeAddress.
     */
    @java.lang.Override
    public java.lang.String getNodeAddress() {
      java.lang.Object ref = nodeAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nodeAddress_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * node address
     * </pre>
     *
     * <code>string node_address = 2;</code>
     * @return The bytes for nodeAddress.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNodeAddressBytes() {
      java.lang.Object ref = nodeAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NODE_TLS_CERT_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString nodeTlsCert_;
    /**
     * <pre>
     * TLS certificate of the node
     * </pre>
     *
     * <code>bytes node_tls_cert = 3;</code>
     * @return The nodeTlsCert.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getNodeTlsCert() {
      return nodeTlsCert_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nodeId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nodeId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nodeAddress_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nodeAddress_);
      }
      if (!nodeTlsCert_.isEmpty()) {
        output.writeBytes(3, nodeTlsCert_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nodeId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nodeId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nodeAddress_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nodeAddress_);
      }
      if (!nodeTlsCert_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, nodeTlsCert_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.chainmaker.pb.discovery.Discovery.Node)) {
        return super.equals(obj);
      }
      org.chainmaker.pb.discovery.Discovery.Node other = (org.chainmaker.pb.discovery.Discovery.Node) obj;

      if (!getNodeId()
          .equals(other.getNodeId())) return false;
      if (!getNodeAddress()
          .equals(other.getNodeAddress())) return false;
      if (!getNodeTlsCert()
          .equals(other.getNodeTlsCert())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NODE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getNodeId().hashCode();
      hash = (37 * hash) + NODE_ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getNodeAddress().hashCode();
      hash = (37 * hash) + NODE_TLS_CERT_FIELD_NUMBER;
      hash = (53 * hash) + getNodeTlsCert().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.chainmaker.pb.discovery.Discovery.Node parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.chainmaker.pb.discovery.Discovery.Node parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.chainmaker.pb.discovery.Discovery.Node parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.chainmaker.pb.discovery.Discovery.Node parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.chainmaker.pb.discovery.Discovery.Node parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.chainmaker.pb.discovery.Discovery.Node parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.chainmaker.pb.discovery.Discovery.Node parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.chainmaker.pb.discovery.Discovery.Node parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.chainmaker.pb.discovery.Discovery.Node parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.chainmaker.pb.discovery.Discovery.Node parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.chainmaker.pb.discovery.Discovery.Node parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.chainmaker.pb.discovery.Discovery.Node parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.chainmaker.pb.discovery.Discovery.Node prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * information of a blockchain node
     * </pre>
     *
     * Protobuf type {@code discovery.Node}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:discovery.Node)
        org.chainmaker.pb.discovery.Discovery.NodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.chainmaker.pb.discovery.Discovery.internal_static_discovery_Node_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.chainmaker.pb.discovery.Discovery.internal_static_discovery_Node_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.chainmaker.pb.discovery.Discovery.Node.class, org.chainmaker.pb.discovery.Discovery.Node.Builder.class);
      }

      // Construct using org.chainmaker.pb.discovery.Discovery.Node.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        nodeId_ = "";

        nodeAddress_ = "";

        nodeTlsCert_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.chainmaker.pb.discovery.Discovery.internal_static_discovery_Node_descriptor;
      }

      @java.lang.Override
      public org.chainmaker.pb.discovery.Discovery.Node getDefaultInstanceForType() {
        return org.chainmaker.pb.discovery.Discovery.Node.getDefaultInstance();
      }

      @java.lang.Override
      public org.chainmaker.pb.discovery.Discovery.Node build() {
        org.chainmaker.pb.discovery.Discovery.Node result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.chainmaker.pb.discovery.Discovery.Node buildPartial() {
        org.chainmaker.pb.discovery.Discovery.Node result = new org.chainmaker.pb.discovery.Discovery.Node(this);
        result.nodeId_ = nodeId_;
        result.nodeAddress_ = nodeAddress_;
        result.nodeTlsCert_ = nodeTlsCert_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.chainmaker.pb.discovery.Discovery.Node) {
          return mergeFrom((org.chainmaker.pb.discovery.Discovery.Node)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.chainmaker.pb.discovery.Discovery.Node other) {
        if (other == org.chainmaker.pb.discovery.Discovery.Node.getDefaultInstance()) return this;
        if (!other.getNodeId().isEmpty()) {
          nodeId_ = other.nodeId_;
          onChanged();
        }
        if (!other.getNodeAddress().isEmpty()) {
          nodeAddress_ = other.nodeAddress_;
          onChanged();
        }
        if (other.getNodeTlsCert() != com.google.protobuf.ByteString.EMPTY) {
          setNodeTlsCert(other.getNodeTlsCert());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.chainmaker.pb.discovery.Discovery.Node parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.chainmaker.pb.discovery.Discovery.Node) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object nodeId_ = "";
      /**
       * <pre>
       * node identifier
       * </pre>
       *
       * <code>string node_id = 1;</code>
       * @return The nodeId.
       */
      public java.lang.String getNodeId() {
        java.lang.Object ref = nodeId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nodeId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * node identifier
       * </pre>
       *
       * <code>string node_id = 1;</code>
       * @return The bytes for nodeId.
       */
      public com.google.protobuf.ByteString
          getNodeIdBytes() {
        java.lang.Object ref = nodeId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nodeId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * node identifier
       * </pre>
       *
       * <code>string node_id = 1;</code>
       * @param value The nodeId to set.
       * @return This builder for chaining.
       */
      public Builder setNodeId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nodeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * node identifier
       * </pre>
       *
       * <code>string node_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNodeId() {
        
        nodeId_ = getDefaultInstance().getNodeId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * node identifier
       * </pre>
       *
       * <code>string node_id = 1;</code>
       * @param value The bytes for nodeId to set.
       * @return This builder for chaining.
       */
      public Builder setNodeIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nodeId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nodeAddress_ = "";
      /**
       * <pre>
       * node address
       * </pre>
       *
       * <code>string node_address = 2;</code>
       * @return The nodeAddress.
       */
      public java.lang.String getNodeAddress() {
        java.lang.Object ref = nodeAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nodeAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * node address
       * </pre>
       *
       * <code>string node_address = 2;</code>
       * @return The bytes for nodeAddress.
       */
      public com.google.protobuf.ByteString
          getNodeAddressBytes() {
        java.lang.Object ref = nodeAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nodeAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * node address
       * </pre>
       *
       * <code>string node_address = 2;</code>
       * @param value The nodeAddress to set.
       * @return This builder for chaining.
       */
      public Builder setNodeAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nodeAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * node address
       * </pre>
       *
       * <code>string node_address = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNodeAddress() {
        
        nodeAddress_ = getDefaultInstance().getNodeAddress();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * node address
       * </pre>
       *
       * <code>string node_address = 2;</code>
       * @param value The bytes for nodeAddress to set.
       * @return This builder for chaining.
       */
      public Builder setNodeAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nodeAddress_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString nodeTlsCert_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * TLS certificate of the node
       * </pre>
       *
       * <code>bytes node_tls_cert = 3;</code>
       * @return The nodeTlsCert.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getNodeTlsCert() {
        return nodeTlsCert_;
      }
      /**
       * <pre>
       * TLS certificate of the node
       * </pre>
       *
       * <code>bytes node_tls_cert = 3;</code>
       * @param value The nodeTlsCert to set.
       * @return This builder for chaining.
       */
      public Builder setNodeTlsCert(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nodeTlsCert_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * TLS certificate of the node
       * </pre>
       *
       * <code>bytes node_tls_cert = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNodeTlsCert() {
        
        nodeTlsCert_ = getDefaultInstance().getNodeTlsCert();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:discovery.Node)
    }

    // @@protoc_insertion_point(class_scope:discovery.Node)
    private static final org.chainmaker.pb.discovery.Discovery.Node DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.chainmaker.pb.discovery.Discovery.Node();
    }

    public static org.chainmaker.pb.discovery.Discovery.Node getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Node>
        PARSER = new com.google.protobuf.AbstractParser<Node>() {
      @java.lang.Override
      public Node parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Node(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Node> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Node> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.chainmaker.pb.discovery.Discovery.Node getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ChainListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:discovery.ChainList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string chain_id_list = 1;</code>
     * @return A list containing the chainIdList.
     */
    java.util.List<java.lang.String>
        getChainIdListList();
    /**
     * <code>repeated string chain_id_list = 1;</code>
     * @return The count of chainIdList.
     */
    int getChainIdListCount();
    /**
     * <code>repeated string chain_id_list = 1;</code>
     * @param index The index of the element to return.
     * @return The chainIdList at the given index.
     */
    java.lang.String getChainIdList(int index);
    /**
     * <code>repeated string chain_id_list = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the chainIdList at the given index.
     */
    com.google.protobuf.ByteString
        getChainIdListBytes(int index);
  }
  /**
   * <pre>
   * chain_id_list
   * </pre>
   *
   * Protobuf type {@code discovery.ChainList}
   */
  public static final class ChainList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:discovery.ChainList)
      ChainListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChainList.newBuilder() to construct.
    private ChainList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChainList() {
      chainIdList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChainList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChainList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                chainIdList_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              chainIdList_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          chainIdList_ = chainIdList_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.chainmaker.pb.discovery.Discovery.internal_static_discovery_ChainList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.chainmaker.pb.discovery.Discovery.internal_static_discovery_ChainList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.chainmaker.pb.discovery.Discovery.ChainList.class, org.chainmaker.pb.discovery.Discovery.ChainList.Builder.class);
    }

    public static final int CHAIN_ID_LIST_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList chainIdList_;
    /**
     * <code>repeated string chain_id_list = 1;</code>
     * @return A list containing the chainIdList.
     */
    public com.google.protobuf.ProtocolStringList
        getChainIdListList() {
      return chainIdList_;
    }
    /**
     * <code>repeated string chain_id_list = 1;</code>
     * @return The count of chainIdList.
     */
    public int getChainIdListCount() {
      return chainIdList_.size();
    }
    /**
     * <code>repeated string chain_id_list = 1;</code>
     * @param index The index of the element to return.
     * @return The chainIdList at the given index.
     */
    public java.lang.String getChainIdList(int index) {
      return chainIdList_.get(index);
    }
    /**
     * <code>repeated string chain_id_list = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the chainIdList at the given index.
     */
    public com.google.protobuf.ByteString
        getChainIdListBytes(int index) {
      return chainIdList_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < chainIdList_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, chainIdList_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < chainIdList_.size(); i++) {
          dataSize += computeStringSizeNoTag(chainIdList_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getChainIdListList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.chainmaker.pb.discovery.Discovery.ChainList)) {
        return super.equals(obj);
      }
      org.chainmaker.pb.discovery.Discovery.ChainList other = (org.chainmaker.pb.discovery.Discovery.ChainList) obj;

      if (!getChainIdListList()
          .equals(other.getChainIdListList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getChainIdListCount() > 0) {
        hash = (37 * hash) + CHAIN_ID_LIST_FIELD_NUMBER;
        hash = (53 * hash) + getChainIdListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.chainmaker.pb.discovery.Discovery.ChainList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.chainmaker.pb.discovery.Discovery.ChainList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.chainmaker.pb.discovery.Discovery.ChainList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.chainmaker.pb.discovery.Discovery.ChainList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.chainmaker.pb.discovery.Discovery.ChainList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.chainmaker.pb.discovery.Discovery.ChainList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.chainmaker.pb.discovery.Discovery.ChainList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.chainmaker.pb.discovery.Discovery.ChainList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.chainmaker.pb.discovery.Discovery.ChainList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.chainmaker.pb.discovery.Discovery.ChainList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.chainmaker.pb.discovery.Discovery.ChainList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.chainmaker.pb.discovery.Discovery.ChainList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.chainmaker.pb.discovery.Discovery.ChainList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * chain_id_list
     * </pre>
     *
     * Protobuf type {@code discovery.ChainList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:discovery.ChainList)
        org.chainmaker.pb.discovery.Discovery.ChainListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.chainmaker.pb.discovery.Discovery.internal_static_discovery_ChainList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.chainmaker.pb.discovery.Discovery.internal_static_discovery_ChainList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.chainmaker.pb.discovery.Discovery.ChainList.class, org.chainmaker.pb.discovery.Discovery.ChainList.Builder.class);
      }

      // Construct using org.chainmaker.pb.discovery.Discovery.ChainList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        chainIdList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.chainmaker.pb.discovery.Discovery.internal_static_discovery_ChainList_descriptor;
      }

      @java.lang.Override
      public org.chainmaker.pb.discovery.Discovery.ChainList getDefaultInstanceForType() {
        return org.chainmaker.pb.discovery.Discovery.ChainList.getDefaultInstance();
      }

      @java.lang.Override
      public org.chainmaker.pb.discovery.Discovery.ChainList build() {
        org.chainmaker.pb.discovery.Discovery.ChainList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.chainmaker.pb.discovery.Discovery.ChainList buildPartial() {
        org.chainmaker.pb.discovery.Discovery.ChainList result = new org.chainmaker.pb.discovery.Discovery.ChainList(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          chainIdList_ = chainIdList_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.chainIdList_ = chainIdList_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.chainmaker.pb.discovery.Discovery.ChainList) {
          return mergeFrom((org.chainmaker.pb.discovery.Discovery.ChainList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.chainmaker.pb.discovery.Discovery.ChainList other) {
        if (other == org.chainmaker.pb.discovery.Discovery.ChainList.getDefaultInstance()) return this;
        if (!other.chainIdList_.isEmpty()) {
          if (chainIdList_.isEmpty()) {
            chainIdList_ = other.chainIdList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureChainIdListIsMutable();
            chainIdList_.addAll(other.chainIdList_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.chainmaker.pb.discovery.Discovery.ChainList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.chainmaker.pb.discovery.Discovery.ChainList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList chainIdList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureChainIdListIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          chainIdList_ = new com.google.protobuf.LazyStringArrayList(chainIdList_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string chain_id_list = 1;</code>
       * @return A list containing the chainIdList.
       */
      public com.google.protobuf.ProtocolStringList
          getChainIdListList() {
        return chainIdList_.getUnmodifiableView();
      }
      /**
       * <code>repeated string chain_id_list = 1;</code>
       * @return The count of chainIdList.
       */
      public int getChainIdListCount() {
        return chainIdList_.size();
      }
      /**
       * <code>repeated string chain_id_list = 1;</code>
       * @param index The index of the element to return.
       * @return The chainIdList at the given index.
       */
      public java.lang.String getChainIdList(int index) {
        return chainIdList_.get(index);
      }
      /**
       * <code>repeated string chain_id_list = 1;</code>
       * @param index The index of the value to return.
       * @return The bytes of the chainIdList at the given index.
       */
      public com.google.protobuf.ByteString
          getChainIdListBytes(int index) {
        return chainIdList_.getByteString(index);
      }
      /**
       * <code>repeated string chain_id_list = 1;</code>
       * @param index The index to set the value at.
       * @param value The chainIdList to set.
       * @return This builder for chaining.
       */
      public Builder setChainIdList(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureChainIdListIsMutable();
        chainIdList_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string chain_id_list = 1;</code>
       * @param value The chainIdList to add.
       * @return This builder for chaining.
       */
      public Builder addChainIdList(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureChainIdListIsMutable();
        chainIdList_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string chain_id_list = 1;</code>
       * @param values The chainIdList to add.
       * @return This builder for chaining.
       */
      public Builder addAllChainIdList(
          java.lang.Iterable<java.lang.String> values) {
        ensureChainIdListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, chainIdList_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string chain_id_list = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearChainIdList() {
        chainIdList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string chain_id_list = 1;</code>
       * @param value The bytes of the chainIdList to add.
       * @return This builder for chaining.
       */
      public Builder addChainIdListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureChainIdListIsMutable();
        chainIdList_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:discovery.ChainList)
    }

    // @@protoc_insertion_point(class_scope:discovery.ChainList)
    private static final org.chainmaker.pb.discovery.Discovery.ChainList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.chainmaker.pb.discovery.Discovery.ChainList();
    }

    public static org.chainmaker.pb.discovery.Discovery.ChainList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChainList>
        PARSER = new com.google.protobuf.AbstractParser<ChainList>() {
      @java.lang.Override
      public ChainList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChainList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChainList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChainList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.chainmaker.pb.discovery.Discovery.ChainList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_discovery_ChainInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_discovery_ChainInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_discovery_Node_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_discovery_Node_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_discovery_ChainList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_discovery_ChainList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031discovery/discovery.proto\022\tdiscovery\"E" +
      "\n\tChainInfo\022\024\n\014block_height\030\001 \001(\004\022\"\n\tnod" +
      "e_list\030\002 \003(\0132\017.discovery.Node\"D\n\004Node\022\017\n" +
      "\007node_id\030\001 \001(\t\022\024\n\014node_address\030\002 \001(\t\022\025\n\r" +
      "node_tls_cert\030\003 \001(\014\"\"\n\tChainList\022\025\n\rchai" +
      "n_id_list\030\001 \003(\tBK\n\033org.chainmaker.pb.dis" +
      "coveryZ,chainmaker.org/chainmaker/pb-go/" +
      "v2/discoveryb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_discovery_ChainInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_discovery_ChainInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_discovery_ChainInfo_descriptor,
        new java.lang.String[] { "BlockHeight", "NodeList", });
    internal_static_discovery_Node_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_discovery_Node_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_discovery_Node_descriptor,
        new java.lang.String[] { "NodeId", "NodeAddress", "NodeTlsCert", });
    internal_static_discovery_ChainList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_discovery_ChainList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_discovery_ChainList_descriptor,
        new java.lang.String[] { "ChainIdList", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
