server:
  port: 8082

spring:
  application:
    name: hello-grpc-java-client

grpc:
  client:
    hello-grpc-server:
      #address: 'dns:///xxx.cluster.local:9991'
      #address: 'discovery:///grpc-server'
      address: 'static://127.0.0.1:10081'
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: PLAINTEXT

