// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: config/local_config.proto

package org.chainmaker.pb.config;

public final class LocalConfig {
  private LocalConfig() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DebugConfigRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:config.DebugConfigRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .config.ConfigKeyValue pairs = 1;</code>
     */
    java.util.List<org.chainmaker.pb.config.ChainConfigOuterClass.ConfigKeyValue> 
        getPairsList();
    /**
     * <code>repeated .config.ConfigKeyValue pairs = 1;</code>
     */
    org.chainmaker.pb.config.ChainConfigOuterClass.ConfigKeyValue getPairs(int index);
    /**
     * <code>repeated .config.ConfigKeyValue pairs = 1;</code>
     */
    int getPairsCount();
    /**
     * <code>repeated .config.ConfigKeyValue pairs = 1;</code>
     */
    java.util.List<? extends org.chainmaker.pb.config.ChainConfigOuterClass.ConfigKeyValueOrBuilder> 
        getPairsOrBuilderList();
    /**
     * <code>repeated .config.ConfigKeyValue pairs = 1;</code>
     */
    org.chainmaker.pb.config.ChainConfigOuterClass.ConfigKeyValueOrBuilder getPairsOrBuilder(
        int index);
  }
  /**
   * <pre>
   * rquest for debug configuration
   * </pre>
   *
   * Protobuf type {@code config.DebugConfigRequest}
   */
  public static final class DebugConfigRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:config.DebugConfigRequest)
      DebugConfigRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DebugConfigRequest.newBuilder() to construct.
    private DebugConfigRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DebugConfigRequest() {
      pairs_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DebugConfigRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DebugConfigRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                pairs_ = new java.util.ArrayList<org.chainmaker.pb.config.ChainConfigOuterClass.ConfigKeyValue>();
                mutable_bitField0_ |= 0x00000001;
              }
              pairs_.add(
                  input.readMessage(org.chainmaker.pb.config.ChainConfigOuterClass.ConfigKeyValue.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          pairs_ = java.util.Collections.unmodifiableList(pairs_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.chainmaker.pb.config.LocalConfig.internal_static_config_DebugConfigRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.chainmaker.pb.config.LocalConfig.internal_static_config_DebugConfigRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.chainmaker.pb.config.LocalConfig.DebugConfigRequest.class, org.chainmaker.pb.config.LocalConfig.DebugConfigRequest.Builder.class);
    }

    public static final int PAIRS_FIELD_NUMBER = 1;
    private java.util.List<org.chainmaker.pb.config.ChainConfigOuterClass.ConfigKeyValue> pairs_;
    /**
     * <code>repeated .config.ConfigKeyValue pairs = 1;</code>
     */
    @java.lang.Override
    public java.util.List<org.chainmaker.pb.config.ChainConfigOuterClass.ConfigKeyValue> getPairsList() {
      return pairs_;
    }
    /**
     * <code>repeated .config.ConfigKeyValue pairs = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.chainmaker.pb.config.ChainConfigOuterClass.ConfigKeyValueOrBuilder> 
        getPairsOrBuilderList() {
      return pairs_;
    }
    /**
     * <code>repeated .config.ConfigKeyValue pairs = 1;</code>
     */
    @java.lang.Override
    public int getPairsCount() {
      return pairs_.size();
    }
    /**
     * <code>repeated .config.ConfigKeyValue pairs = 1;</code>
     */
    @java.lang.Override
    public org.chainmaker.pb.config.ChainConfigOuterClass.ConfigKeyValue getPairs(int index) {
      return pairs_.get(index);
    }
    /**
     * <code>repeated .config.ConfigKeyValue pairs = 1;</code>
     */
    @java.lang.Override
    public org.chainmaker.pb.config.ChainConfigOuterClass.ConfigKeyValueOrBuilder getPairsOrBuilder(
        int index) {
      return pairs_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < pairs_.size(); i++) {
        output.writeMessage(1, pairs_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < pairs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, pairs_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.chainmaker.pb.config.LocalConfig.DebugConfigRequest)) {
        return super.equals(obj);
      }
      org.chainmaker.pb.config.LocalConfig.DebugConfigRequest other = (org.chainmaker.pb.config.LocalConfig.DebugConfigRequest) obj;

      if (!getPairsList()
          .equals(other.getPairsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPairsCount() > 0) {
        hash = (37 * hash) + PAIRS_FIELD_NUMBER;
        hash = (53 * hash) + getPairsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.chainmaker.pb.config.LocalConfig.DebugConfigRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.chainmaker.pb.config.LocalConfig.DebugConfigRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.chainmaker.pb.config.LocalConfig.DebugConfigRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.chainmaker.pb.config.LocalConfig.DebugConfigRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.chainmaker.pb.config.LocalConfig.DebugConfigRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.chainmaker.pb.config.LocalConfig.DebugConfigRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.chainmaker.pb.config.LocalConfig.DebugConfigRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.chainmaker.pb.config.LocalConfig.DebugConfigRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.chainmaker.pb.config.LocalConfig.DebugConfigRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.chainmaker.pb.config.LocalConfig.DebugConfigRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.chainmaker.pb.config.LocalConfig.DebugConfigRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.chainmaker.pb.config.LocalConfig.DebugConfigRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.chainmaker.pb.config.LocalConfig.DebugConfigRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * rquest for debug configuration
     * </pre>
     *
     * Protobuf type {@code config.DebugConfigRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:config.DebugConfigRequest)
        org.chainmaker.pb.config.LocalConfig.DebugConfigRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.chainmaker.pb.config.LocalConfig.internal_static_config_DebugConfigRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.chainmaker.pb.config.LocalConfig.internal_static_config_DebugConfigRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.chainmaker.pb.config.LocalConfig.DebugConfigRequest.class, org.chainmaker.pb.config.LocalConfig.DebugConfigRequest.Builder.class);
      }

      // Construct using org.chainmaker.pb.config.LocalConfig.DebugConfigRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPairsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (pairsBuilder_ == null) {
          pairs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          pairsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.chainmaker.pb.config.LocalConfig.internal_static_config_DebugConfigRequest_descriptor;
      }

      @java.lang.Override
      public org.chainmaker.pb.config.LocalConfig.DebugConfigRequest getDefaultInstanceForType() {
        return org.chainmaker.pb.config.LocalConfig.DebugConfigRequest.getDefaultInstance();
      }

      @java.lang.Override
      public org.chainmaker.pb.config.LocalConfig.DebugConfigRequest build() {
        org.chainmaker.pb.config.LocalConfig.DebugConfigRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.chainmaker.pb.config.LocalConfig.DebugConfigRequest buildPartial() {
        org.chainmaker.pb.config.LocalConfig.DebugConfigRequest result = new org.chainmaker.pb.config.LocalConfig.DebugConfigRequest(this);
        int from_bitField0_ = bitField0_;
        if (pairsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            pairs_ = java.util.Collections.unmodifiableList(pairs_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.pairs_ = pairs_;
        } else {
          result.pairs_ = pairsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.chainmaker.pb.config.LocalConfig.DebugConfigRequest) {
          return mergeFrom((org.chainmaker.pb.config.LocalConfig.DebugConfigRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.chainmaker.pb.config.LocalConfig.DebugConfigRequest other) {
        if (other == org.chainmaker.pb.config.LocalConfig.DebugConfigRequest.getDefaultInstance()) return this;
        if (pairsBuilder_ == null) {
          if (!other.pairs_.isEmpty()) {
            if (pairs_.isEmpty()) {
              pairs_ = other.pairs_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePairsIsMutable();
              pairs_.addAll(other.pairs_);
            }
            onChanged();
          }
        } else {
          if (!other.pairs_.isEmpty()) {
            if (pairsBuilder_.isEmpty()) {
              pairsBuilder_.dispose();
              pairsBuilder_ = null;
              pairs_ = other.pairs_;
              bitField0_ = (bitField0_ & ~0x00000001);
              pairsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPairsFieldBuilder() : null;
            } else {
              pairsBuilder_.addAllMessages(other.pairs_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.chainmaker.pb.config.LocalConfig.DebugConfigRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.chainmaker.pb.config.LocalConfig.DebugConfigRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<org.chainmaker.pb.config.ChainConfigOuterClass.ConfigKeyValue> pairs_ =
        java.util.Collections.emptyList();
      private void ensurePairsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          pairs_ = new java.util.ArrayList<org.chainmaker.pb.config.ChainConfigOuterClass.ConfigKeyValue>(pairs_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.chainmaker.pb.config.ChainConfigOuterClass.ConfigKeyValue, org.chainmaker.pb.config.ChainConfigOuterClass.ConfigKeyValue.Builder, org.chainmaker.pb.config.ChainConfigOuterClass.ConfigKeyValueOrBuilder> pairsBuilder_;

      /**
       * <code>repeated .config.ConfigKeyValue pairs = 1;</code>
       */
      public java.util.List<org.chainmaker.pb.config.ChainConfigOuterClass.ConfigKeyValue> getPairsList() {
        if (pairsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(pairs_);
        } else {
          return pairsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .config.ConfigKeyValue pairs = 1;</code>
       */
      public int getPairsCount() {
        if (pairsBuilder_ == null) {
          return pairs_.size();
        } else {
          return pairsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .config.ConfigKeyValue pairs = 1;</code>
       */
      public org.chainmaker.pb.config.ChainConfigOuterClass.ConfigKeyValue getPairs(int index) {
        if (pairsBuilder_ == null) {
          return pairs_.get(index);
        } else {
          return pairsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .config.ConfigKeyValue pairs = 1;</code>
       */
      public Builder setPairs(
          int index, org.chainmaker.pb.config.ChainConfigOuterClass.ConfigKeyValue value) {
        if (pairsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePairsIsMutable();
          pairs_.set(index, value);
          onChanged();
        } else {
          pairsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .config.ConfigKeyValue pairs = 1;</code>
       */
      public Builder setPairs(
          int index, org.chainmaker.pb.config.ChainConfigOuterClass.ConfigKeyValue.Builder builderForValue) {
        if (pairsBuilder_ == null) {
          ensurePairsIsMutable();
          pairs_.set(index, builderForValue.build());
          onChanged();
        } else {
          pairsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .config.ConfigKeyValue pairs = 1;</code>
       */
      public Builder addPairs(org.chainmaker.pb.config.ChainConfigOuterClass.ConfigKeyValue value) {
        if (pairsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePairsIsMutable();
          pairs_.add(value);
          onChanged();
        } else {
          pairsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .config.ConfigKeyValue pairs = 1;</code>
       */
      public Builder addPairs(
          int index, org.chainmaker.pb.config.ChainConfigOuterClass.ConfigKeyValue value) {
        if (pairsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePairsIsMutable();
          pairs_.add(index, value);
          onChanged();
        } else {
          pairsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .config.ConfigKeyValue pairs = 1;</code>
       */
      public Builder addPairs(
          org.chainmaker.pb.config.ChainConfigOuterClass.ConfigKeyValue.Builder builderForValue) {
        if (pairsBuilder_ == null) {
          ensurePairsIsMutable();
          pairs_.add(builderForValue.build());
          onChanged();
        } else {
          pairsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .config.ConfigKeyValue pairs = 1;</code>
       */
      public Builder addPairs(
          int index, org.chainmaker.pb.config.ChainConfigOuterClass.ConfigKeyValue.Builder builderForValue) {
        if (pairsBuilder_ == null) {
          ensurePairsIsMutable();
          pairs_.add(index, builderForValue.build());
          onChanged();
        } else {
          pairsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .config.ConfigKeyValue pairs = 1;</code>
       */
      public Builder addAllPairs(
          java.lang.Iterable<? extends org.chainmaker.pb.config.ChainConfigOuterClass.ConfigKeyValue> values) {
        if (pairsBuilder_ == null) {
          ensurePairsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, pairs_);
          onChanged();
        } else {
          pairsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .config.ConfigKeyValue pairs = 1;</code>
       */
      public Builder clearPairs() {
        if (pairsBuilder_ == null) {
          pairs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          pairsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .config.ConfigKeyValue pairs = 1;</code>
       */
      public Builder removePairs(int index) {
        if (pairsBuilder_ == null) {
          ensurePairsIsMutable();
          pairs_.remove(index);
          onChanged();
        } else {
          pairsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .config.ConfigKeyValue pairs = 1;</code>
       */
      public org.chainmaker.pb.config.ChainConfigOuterClass.ConfigKeyValue.Builder getPairsBuilder(
          int index) {
        return getPairsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .config.ConfigKeyValue pairs = 1;</code>
       */
      public org.chainmaker.pb.config.ChainConfigOuterClass.ConfigKeyValueOrBuilder getPairsOrBuilder(
          int index) {
        if (pairsBuilder_ == null) {
          return pairs_.get(index);  } else {
          return pairsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .config.ConfigKeyValue pairs = 1;</code>
       */
      public java.util.List<? extends org.chainmaker.pb.config.ChainConfigOuterClass.ConfigKeyValueOrBuilder> 
           getPairsOrBuilderList() {
        if (pairsBuilder_ != null) {
          return pairsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(pairs_);
        }
      }
      /**
       * <code>repeated .config.ConfigKeyValue pairs = 1;</code>
       */
      public org.chainmaker.pb.config.ChainConfigOuterClass.ConfigKeyValue.Builder addPairsBuilder() {
        return getPairsFieldBuilder().addBuilder(
            org.chainmaker.pb.config.ChainConfigOuterClass.ConfigKeyValue.getDefaultInstance());
      }
      /**
       * <code>repeated .config.ConfigKeyValue pairs = 1;</code>
       */
      public org.chainmaker.pb.config.ChainConfigOuterClass.ConfigKeyValue.Builder addPairsBuilder(
          int index) {
        return getPairsFieldBuilder().addBuilder(
            index, org.chainmaker.pb.config.ChainConfigOuterClass.ConfigKeyValue.getDefaultInstance());
      }
      /**
       * <code>repeated .config.ConfigKeyValue pairs = 1;</code>
       */
      public java.util.List<org.chainmaker.pb.config.ChainConfigOuterClass.ConfigKeyValue.Builder> 
           getPairsBuilderList() {
        return getPairsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.chainmaker.pb.config.ChainConfigOuterClass.ConfigKeyValue, org.chainmaker.pb.config.ChainConfigOuterClass.ConfigKeyValue.Builder, org.chainmaker.pb.config.ChainConfigOuterClass.ConfigKeyValueOrBuilder> 
          getPairsFieldBuilder() {
        if (pairsBuilder_ == null) {
          pairsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.chainmaker.pb.config.ChainConfigOuterClass.ConfigKeyValue, org.chainmaker.pb.config.ChainConfigOuterClass.ConfigKeyValue.Builder, org.chainmaker.pb.config.ChainConfigOuterClass.ConfigKeyValueOrBuilder>(
                  pairs_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          pairs_ = null;
        }
        return pairsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:config.DebugConfigRequest)
    }

    // @@protoc_insertion_point(class_scope:config.DebugConfigRequest)
    private static final org.chainmaker.pb.config.LocalConfig.DebugConfigRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.chainmaker.pb.config.LocalConfig.DebugConfigRequest();
    }

    public static org.chainmaker.pb.config.LocalConfig.DebugConfigRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DebugConfigRequest>
        PARSER = new com.google.protobuf.AbstractParser<DebugConfigRequest>() {
      @java.lang.Override
      public DebugConfigRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DebugConfigRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DebugConfigRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DebugConfigRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.chainmaker.pb.config.LocalConfig.DebugConfigRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DebugConfigResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:config.DebugConfigResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 0 success
     * 1 fail
     * </pre>
     *
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    int getCode();

    /**
     * <pre>
     * failure message
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <pre>
     * failure message
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * <pre>
   * Rrsponse for debug configuration
   * </pre>
   *
   * Protobuf type {@code config.DebugConfigResponse}
   */
  public static final class DebugConfigResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:config.DebugConfigResponse)
      DebugConfigResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DebugConfigResponse.newBuilder() to construct.
    private DebugConfigResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DebugConfigResponse() {
      message_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DebugConfigResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DebugConfigResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              code_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.chainmaker.pb.config.LocalConfig.internal_static_config_DebugConfigResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.chainmaker.pb.config.LocalConfig.internal_static_config_DebugConfigResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.chainmaker.pb.config.LocalConfig.DebugConfigResponse.class, org.chainmaker.pb.config.LocalConfig.DebugConfigResponse.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <pre>
     * 0 success
     * 1 fail
     * </pre>
     *
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    @java.lang.Override
    public int getCode() {
      return code_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object message_;
    /**
     * <pre>
     * failure message
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * failure message
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != 0) {
        output.writeInt32(1, code_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.chainmaker.pb.config.LocalConfig.DebugConfigResponse)) {
        return super.equals(obj);
      }
      org.chainmaker.pb.config.LocalConfig.DebugConfigResponse other = (org.chainmaker.pb.config.LocalConfig.DebugConfigResponse) obj;

      if (getCode()
          != other.getCode()) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.chainmaker.pb.config.LocalConfig.DebugConfigResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.chainmaker.pb.config.LocalConfig.DebugConfigResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.chainmaker.pb.config.LocalConfig.DebugConfigResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.chainmaker.pb.config.LocalConfig.DebugConfigResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.chainmaker.pb.config.LocalConfig.DebugConfigResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.chainmaker.pb.config.LocalConfig.DebugConfigResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.chainmaker.pb.config.LocalConfig.DebugConfigResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.chainmaker.pb.config.LocalConfig.DebugConfigResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.chainmaker.pb.config.LocalConfig.DebugConfigResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.chainmaker.pb.config.LocalConfig.DebugConfigResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.chainmaker.pb.config.LocalConfig.DebugConfigResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.chainmaker.pb.config.LocalConfig.DebugConfigResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.chainmaker.pb.config.LocalConfig.DebugConfigResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Rrsponse for debug configuration
     * </pre>
     *
     * Protobuf type {@code config.DebugConfigResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:config.DebugConfigResponse)
        org.chainmaker.pb.config.LocalConfig.DebugConfigResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.chainmaker.pb.config.LocalConfig.internal_static_config_DebugConfigResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.chainmaker.pb.config.LocalConfig.internal_static_config_DebugConfigResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.chainmaker.pb.config.LocalConfig.DebugConfigResponse.class, org.chainmaker.pb.config.LocalConfig.DebugConfigResponse.Builder.class);
      }

      // Construct using org.chainmaker.pb.config.LocalConfig.DebugConfigResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        code_ = 0;

        message_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.chainmaker.pb.config.LocalConfig.internal_static_config_DebugConfigResponse_descriptor;
      }

      @java.lang.Override
      public org.chainmaker.pb.config.LocalConfig.DebugConfigResponse getDefaultInstanceForType() {
        return org.chainmaker.pb.config.LocalConfig.DebugConfigResponse.getDefaultInstance();
      }

      @java.lang.Override
      public org.chainmaker.pb.config.LocalConfig.DebugConfigResponse build() {
        org.chainmaker.pb.config.LocalConfig.DebugConfigResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.chainmaker.pb.config.LocalConfig.DebugConfigResponse buildPartial() {
        org.chainmaker.pb.config.LocalConfig.DebugConfigResponse result = new org.chainmaker.pb.config.LocalConfig.DebugConfigResponse(this);
        result.code_ = code_;
        result.message_ = message_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.chainmaker.pb.config.LocalConfig.DebugConfigResponse) {
          return mergeFrom((org.chainmaker.pb.config.LocalConfig.DebugConfigResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.chainmaker.pb.config.LocalConfig.DebugConfigResponse other) {
        if (other == org.chainmaker.pb.config.LocalConfig.DebugConfigResponse.getDefaultInstance()) return this;
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.chainmaker.pb.config.LocalConfig.DebugConfigResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.chainmaker.pb.config.LocalConfig.DebugConfigResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int code_ ;
      /**
       * <pre>
       * 0 success
       * 1 fail
       * </pre>
       *
       * <code>int32 code = 1;</code>
       * @return The code.
       */
      @java.lang.Override
      public int getCode() {
        return code_;
      }
      /**
       * <pre>
       * 0 success
       * 1 fail
       * </pre>
       *
       * <code>int32 code = 1;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 0 success
       * 1 fail
       * </pre>
       *
       * <code>int32 code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <pre>
       * failure message
       * </pre>
       *
       * <code>string message = 2;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * failure message
       * </pre>
       *
       * <code>string message = 2;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * failure message
       * </pre>
       *
       * <code>string message = 2;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * failure message
       * </pre>
       *
       * <code>string message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * failure message
       * </pre>
       *
       * <code>string message = 2;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:config.DebugConfigResponse)
    }

    // @@protoc_insertion_point(class_scope:config.DebugConfigResponse)
    private static final org.chainmaker.pb.config.LocalConfig.DebugConfigResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.chainmaker.pb.config.LocalConfig.DebugConfigResponse();
    }

    public static org.chainmaker.pb.config.LocalConfig.DebugConfigResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DebugConfigResponse>
        PARSER = new com.google.protobuf.AbstractParser<DebugConfigResponse>() {
      @java.lang.Override
      public DebugConfigResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DebugConfigResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DebugConfigResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DebugConfigResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.chainmaker.pb.config.LocalConfig.DebugConfigResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CheckNewBlockChainConfigRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:config.CheckNewBlockChainConfigRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * request for check new block configuration
   * </pre>
   *
   * Protobuf type {@code config.CheckNewBlockChainConfigRequest}
   */
  public static final class CheckNewBlockChainConfigRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:config.CheckNewBlockChainConfigRequest)
      CheckNewBlockChainConfigRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CheckNewBlockChainConfigRequest.newBuilder() to construct.
    private CheckNewBlockChainConfigRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CheckNewBlockChainConfigRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CheckNewBlockChainConfigRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CheckNewBlockChainConfigRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.chainmaker.pb.config.LocalConfig.internal_static_config_CheckNewBlockChainConfigRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.chainmaker.pb.config.LocalConfig.internal_static_config_CheckNewBlockChainConfigRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigRequest.class, org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigRequest)) {
        return super.equals(obj);
      }
      org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigRequest other = (org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigRequest) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * request for check new block configuration
     * </pre>
     *
     * Protobuf type {@code config.CheckNewBlockChainConfigRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:config.CheckNewBlockChainConfigRequest)
        org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.chainmaker.pb.config.LocalConfig.internal_static_config_CheckNewBlockChainConfigRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.chainmaker.pb.config.LocalConfig.internal_static_config_CheckNewBlockChainConfigRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigRequest.class, org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigRequest.Builder.class);
      }

      // Construct using org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.chainmaker.pb.config.LocalConfig.internal_static_config_CheckNewBlockChainConfigRequest_descriptor;
      }

      @java.lang.Override
      public org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigRequest getDefaultInstanceForType() {
        return org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigRequest.getDefaultInstance();
      }

      @java.lang.Override
      public org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigRequest build() {
        org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigRequest buildPartial() {
        org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigRequest result = new org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigRequest(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigRequest) {
          return mergeFrom((org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigRequest other) {
        if (other == org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:config.CheckNewBlockChainConfigRequest)
    }

    // @@protoc_insertion_point(class_scope:config.CheckNewBlockChainConfigRequest)
    private static final org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigRequest();
    }

    public static org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CheckNewBlockChainConfigRequest>
        PARSER = new com.google.protobuf.AbstractParser<CheckNewBlockChainConfigRequest>() {
      @java.lang.Override
      public CheckNewBlockChainConfigRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CheckNewBlockChainConfigRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CheckNewBlockChainConfigRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CheckNewBlockChainConfigRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CheckNewBlockChainConfigResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:config.CheckNewBlockChainConfigResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 0 success
     * 1 fail
     * </pre>
     *
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    int getCode();

    /**
     * <pre>
     * failure message
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <pre>
     * failure message
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * <pre>
   * response for check new block configuration
   * </pre>
   *
   * Protobuf type {@code config.CheckNewBlockChainConfigResponse}
   */
  public static final class CheckNewBlockChainConfigResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:config.CheckNewBlockChainConfigResponse)
      CheckNewBlockChainConfigResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CheckNewBlockChainConfigResponse.newBuilder() to construct.
    private CheckNewBlockChainConfigResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CheckNewBlockChainConfigResponse() {
      message_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CheckNewBlockChainConfigResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CheckNewBlockChainConfigResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              code_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.chainmaker.pb.config.LocalConfig.internal_static_config_CheckNewBlockChainConfigResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.chainmaker.pb.config.LocalConfig.internal_static_config_CheckNewBlockChainConfigResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigResponse.class, org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigResponse.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <pre>
     * 0 success
     * 1 fail
     * </pre>
     *
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    @java.lang.Override
    public int getCode() {
      return code_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object message_;
    /**
     * <pre>
     * failure message
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * failure message
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != 0) {
        output.writeInt32(1, code_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigResponse)) {
        return super.equals(obj);
      }
      org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigResponse other = (org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigResponse) obj;

      if (getCode()
          != other.getCode()) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * response for check new block configuration
     * </pre>
     *
     * Protobuf type {@code config.CheckNewBlockChainConfigResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:config.CheckNewBlockChainConfigResponse)
        org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.chainmaker.pb.config.LocalConfig.internal_static_config_CheckNewBlockChainConfigResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.chainmaker.pb.config.LocalConfig.internal_static_config_CheckNewBlockChainConfigResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigResponse.class, org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigResponse.Builder.class);
      }

      // Construct using org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        code_ = 0;

        message_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.chainmaker.pb.config.LocalConfig.internal_static_config_CheckNewBlockChainConfigResponse_descriptor;
      }

      @java.lang.Override
      public org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigResponse getDefaultInstanceForType() {
        return org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigResponse.getDefaultInstance();
      }

      @java.lang.Override
      public org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigResponse build() {
        org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigResponse buildPartial() {
        org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigResponse result = new org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigResponse(this);
        result.code_ = code_;
        result.message_ = message_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigResponse) {
          return mergeFrom((org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigResponse other) {
        if (other == org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigResponse.getDefaultInstance()) return this;
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int code_ ;
      /**
       * <pre>
       * 0 success
       * 1 fail
       * </pre>
       *
       * <code>int32 code = 1;</code>
       * @return The code.
       */
      @java.lang.Override
      public int getCode() {
        return code_;
      }
      /**
       * <pre>
       * 0 success
       * 1 fail
       * </pre>
       *
       * <code>int32 code = 1;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 0 success
       * 1 fail
       * </pre>
       *
       * <code>int32 code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <pre>
       * failure message
       * </pre>
       *
       * <code>string message = 2;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * failure message
       * </pre>
       *
       * <code>string message = 2;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * failure message
       * </pre>
       *
       * <code>string message = 2;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * failure message
       * </pre>
       *
       * <code>string message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * failure message
       * </pre>
       *
       * <code>string message = 2;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:config.CheckNewBlockChainConfigResponse)
    }

    // @@protoc_insertion_point(class_scope:config.CheckNewBlockChainConfigResponse)
    private static final org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigResponse();
    }

    public static org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CheckNewBlockChainConfigResponse>
        PARSER = new com.google.protobuf.AbstractParser<CheckNewBlockChainConfigResponse>() {
      @java.lang.Override
      public CheckNewBlockChainConfigResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CheckNewBlockChainConfigResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CheckNewBlockChainConfigResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CheckNewBlockChainConfigResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.chainmaker.pb.config.LocalConfig.CheckNewBlockChainConfigResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_config_DebugConfigRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_config_DebugConfigRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_config_DebugConfigResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_config_DebugConfigResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_config_CheckNewBlockChainConfigRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_config_CheckNewBlockChainConfigRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_config_CheckNewBlockChainConfigResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_config_CheckNewBlockChainConfigResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031config/local_config.proto\022\006config\032\031con" +
      "fig/chain_config.proto\";\n\022DebugConfigReq" +
      "uest\022%\n\005pairs\030\001 \003(\0132\026.config.ConfigKeyVa" +
      "lue\"4\n\023DebugConfigResponse\022\014\n\004code\030\001 \001(\005" +
      "\022\017\n\007message\030\002 \001(\t\"!\n\037CheckNewBlockChainC" +
      "onfigRequest\"A\n CheckNewBlockChainConfig" +
      "Response\022\014\n\004code\030\001 \001(\005\022\017\n\007message\030\002 \001(\tB" +
      "E\n\030org.chainmaker.pb.configZ)chainmaker." +
      "org/chainmaker/pb-go/v2/configb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.chainmaker.pb.config.ChainConfigOuterClass.getDescriptor(),
        });
    internal_static_config_DebugConfigRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_config_DebugConfigRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_config_DebugConfigRequest_descriptor,
        new java.lang.String[] { "Pairs", });
    internal_static_config_DebugConfigResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_config_DebugConfigResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_config_DebugConfigResponse_descriptor,
        new java.lang.String[] { "Code", "Message", });
    internal_static_config_CheckNewBlockChainConfigRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_config_CheckNewBlockChainConfigRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_config_CheckNewBlockChainConfigRequest_descriptor,
        new java.lang.String[] { });
    internal_static_config_CheckNewBlockChainConfigResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_config_CheckNewBlockChainConfigResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_config_CheckNewBlockChainConfigResponse_descriptor,
        new java.lang.String[] { "Code", "Message", });
    org.chainmaker.pb.config.ChainConfigOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
