server:
  port: 8081

spring:
  application:
    name: hello-grpc-sever

grpc:
  server:
    address: 0.0.0.0
    port: 10081
    security:
      enabled: false

logging:
  level:
    com:
      jd:
        hello:
          grpc: debug

