// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: net/net.proto

package org.chainmaker.pb.net;

public final class Net {
  private Net() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.Msg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.net.NetMsg msg = 1;</code>
     * @return Whether the msg field is set.
     */
    boolean hasMsg();
    /**
     * <code>.net.NetMsg msg = 1;</code>
     * @return The msg.
     */
    org.chainmaker.pb.net.Net.NetMsg getMsg();
    /**
     * <code>.net.NetMsg msg = 1;</code>
     */
    org.chainmaker.pb.net.Net.NetMsgOrBuilder getMsgOrBuilder();

    /**
     * <code>string chain_id = 2;</code>
     * @return The chainId.
     */
    java.lang.String getChainId();
    /**
     * <code>string chain_id = 2;</code>
     * @return The bytes for chainId.
     */
    com.google.protobuf.ByteString
        getChainIdBytes();

    /**
     * <pre>
     * 属于那个模块，判断消息类型
     * </pre>
     *
     * <code>string flag = 3;</code>
     * @return The flag.
     */
    java.lang.String getFlag();
    /**
     * <pre>
     * 属于那个模块，判断消息类型
     * </pre>
     *
     * <code>string flag = 3;</code>
     * @return The bytes for flag.
     */
    com.google.protobuf.ByteString
        getFlagBytes();
  }
  /**
   * <pre>
   * wrapped network message
   * </pre>
   *
   * Protobuf type {@code net.Msg}
   */
  public static final class Msg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:net.Msg)
      MsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Msg.newBuilder() to construct.
    private Msg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Msg() {
      chainId_ = "";
      flag_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Msg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Msg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.chainmaker.pb.net.Net.NetMsg.Builder subBuilder = null;
              if (msg_ != null) {
                subBuilder = msg_.toBuilder();
              }
              msg_ = input.readMessage(org.chainmaker.pb.net.Net.NetMsg.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(msg_);
                msg_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              chainId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              flag_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.chainmaker.pb.net.Net.internal_static_net_Msg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.chainmaker.pb.net.Net.internal_static_net_Msg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.chainmaker.pb.net.Net.Msg.class, org.chainmaker.pb.net.Net.Msg.Builder.class);
    }

    public static final int MSG_FIELD_NUMBER = 1;
    private org.chainmaker.pb.net.Net.NetMsg msg_;
    /**
     * <code>.net.NetMsg msg = 1;</code>
     * @return Whether the msg field is set.
     */
    @java.lang.Override
    public boolean hasMsg() {
      return msg_ != null;
    }
    /**
     * <code>.net.NetMsg msg = 1;</code>
     * @return The msg.
     */
    @java.lang.Override
    public org.chainmaker.pb.net.Net.NetMsg getMsg() {
      return msg_ == null ? org.chainmaker.pb.net.Net.NetMsg.getDefaultInstance() : msg_;
    }
    /**
     * <code>.net.NetMsg msg = 1;</code>
     */
    @java.lang.Override
    public org.chainmaker.pb.net.Net.NetMsgOrBuilder getMsgOrBuilder() {
      return getMsg();
    }

    public static final int CHAIN_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object chainId_;
    /**
     * <code>string chain_id = 2;</code>
     * @return The chainId.
     */
    @java.lang.Override
    public java.lang.String getChainId() {
      java.lang.Object ref = chainId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        chainId_ = s;
        return s;
      }
    }
    /**
     * <code>string chain_id = 2;</code>
     * @return The bytes for chainId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getChainIdBytes() {
      java.lang.Object ref = chainId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chainId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FLAG_FIELD_NUMBER = 3;
    private volatile java.lang.Object flag_;
    /**
     * <pre>
     * 属于那个模块，判断消息类型
     * </pre>
     *
     * <code>string flag = 3;</code>
     * @return The flag.
     */
    @java.lang.Override
    public java.lang.String getFlag() {
      java.lang.Object ref = flag_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        flag_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 属于那个模块，判断消息类型
     * </pre>
     *
     * <code>string flag = 3;</code>
     * @return The bytes for flag.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFlagBytes() {
      java.lang.Object ref = flag_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        flag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msg_ != null) {
        output.writeMessage(1, getMsg());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(chainId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, chainId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(flag_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, flag_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msg_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMsg());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(chainId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, chainId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(flag_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, flag_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.chainmaker.pb.net.Net.Msg)) {
        return super.equals(obj);
      }
      org.chainmaker.pb.net.Net.Msg other = (org.chainmaker.pb.net.Net.Msg) obj;

      if (hasMsg() != other.hasMsg()) return false;
      if (hasMsg()) {
        if (!getMsg()
            .equals(other.getMsg())) return false;
      }
      if (!getChainId()
          .equals(other.getChainId())) return false;
      if (!getFlag()
          .equals(other.getFlag())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMsg()) {
        hash = (37 * hash) + MSG_FIELD_NUMBER;
        hash = (53 * hash) + getMsg().hashCode();
      }
      hash = (37 * hash) + CHAIN_ID_FIELD_NUMBER;
      hash = (53 * hash) + getChainId().hashCode();
      hash = (37 * hash) + FLAG_FIELD_NUMBER;
      hash = (53 * hash) + getFlag().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.chainmaker.pb.net.Net.Msg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.chainmaker.pb.net.Net.Msg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.chainmaker.pb.net.Net.Msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.chainmaker.pb.net.Net.Msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.chainmaker.pb.net.Net.Msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.chainmaker.pb.net.Net.Msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.chainmaker.pb.net.Net.Msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.chainmaker.pb.net.Net.Msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.chainmaker.pb.net.Net.Msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.chainmaker.pb.net.Net.Msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.chainmaker.pb.net.Net.Msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.chainmaker.pb.net.Net.Msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.chainmaker.pb.net.Net.Msg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * wrapped network message
     * </pre>
     *
     * Protobuf type {@code net.Msg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:net.Msg)
        org.chainmaker.pb.net.Net.MsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.chainmaker.pb.net.Net.internal_static_net_Msg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.chainmaker.pb.net.Net.internal_static_net_Msg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.chainmaker.pb.net.Net.Msg.class, org.chainmaker.pb.net.Net.Msg.Builder.class);
      }

      // Construct using org.chainmaker.pb.net.Net.Msg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (msgBuilder_ == null) {
          msg_ = null;
        } else {
          msg_ = null;
          msgBuilder_ = null;
        }
        chainId_ = "";

        flag_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.chainmaker.pb.net.Net.internal_static_net_Msg_descriptor;
      }

      @java.lang.Override
      public org.chainmaker.pb.net.Net.Msg getDefaultInstanceForType() {
        return org.chainmaker.pb.net.Net.Msg.getDefaultInstance();
      }

      @java.lang.Override
      public org.chainmaker.pb.net.Net.Msg build() {
        org.chainmaker.pb.net.Net.Msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.chainmaker.pb.net.Net.Msg buildPartial() {
        org.chainmaker.pb.net.Net.Msg result = new org.chainmaker.pb.net.Net.Msg(this);
        if (msgBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = msgBuilder_.build();
        }
        result.chainId_ = chainId_;
        result.flag_ = flag_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.chainmaker.pb.net.Net.Msg) {
          return mergeFrom((org.chainmaker.pb.net.Net.Msg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.chainmaker.pb.net.Net.Msg other) {
        if (other == org.chainmaker.pb.net.Net.Msg.getDefaultInstance()) return this;
        if (other.hasMsg()) {
          mergeMsg(other.getMsg());
        }
        if (!other.getChainId().isEmpty()) {
          chainId_ = other.chainId_;
          onChanged();
        }
        if (!other.getFlag().isEmpty()) {
          flag_ = other.flag_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.chainmaker.pb.net.Net.Msg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.chainmaker.pb.net.Net.Msg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private org.chainmaker.pb.net.Net.NetMsg msg_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.chainmaker.pb.net.Net.NetMsg, org.chainmaker.pb.net.Net.NetMsg.Builder, org.chainmaker.pb.net.Net.NetMsgOrBuilder> msgBuilder_;
      /**
       * <code>.net.NetMsg msg = 1;</code>
       * @return Whether the msg field is set.
       */
      public boolean hasMsg() {
        return msgBuilder_ != null || msg_ != null;
      }
      /**
       * <code>.net.NetMsg msg = 1;</code>
       * @return The msg.
       */
      public org.chainmaker.pb.net.Net.NetMsg getMsg() {
        if (msgBuilder_ == null) {
          return msg_ == null ? org.chainmaker.pb.net.Net.NetMsg.getDefaultInstance() : msg_;
        } else {
          return msgBuilder_.getMessage();
        }
      }
      /**
       * <code>.net.NetMsg msg = 1;</code>
       */
      public Builder setMsg(org.chainmaker.pb.net.Net.NetMsg value) {
        if (msgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
          onChanged();
        } else {
          msgBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.net.NetMsg msg = 1;</code>
       */
      public Builder setMsg(
          org.chainmaker.pb.net.Net.NetMsg.Builder builderForValue) {
        if (msgBuilder_ == null) {
          msg_ = builderForValue.build();
          onChanged();
        } else {
          msgBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.net.NetMsg msg = 1;</code>
       */
      public Builder mergeMsg(org.chainmaker.pb.net.Net.NetMsg value) {
        if (msgBuilder_ == null) {
          if (msg_ != null) {
            msg_ =
              org.chainmaker.pb.net.Net.NetMsg.newBuilder(msg_).mergeFrom(value).buildPartial();
          } else {
            msg_ = value;
          }
          onChanged();
        } else {
          msgBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.net.NetMsg msg = 1;</code>
       */
      public Builder clearMsg() {
        if (msgBuilder_ == null) {
          msg_ = null;
          onChanged();
        } else {
          msg_ = null;
          msgBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.net.NetMsg msg = 1;</code>
       */
      public org.chainmaker.pb.net.Net.NetMsg.Builder getMsgBuilder() {
        
        onChanged();
        return getMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>.net.NetMsg msg = 1;</code>
       */
      public org.chainmaker.pb.net.Net.NetMsgOrBuilder getMsgOrBuilder() {
        if (msgBuilder_ != null) {
          return msgBuilder_.getMessageOrBuilder();
        } else {
          return msg_ == null ?
              org.chainmaker.pb.net.Net.NetMsg.getDefaultInstance() : msg_;
        }
      }
      /**
       * <code>.net.NetMsg msg = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.chainmaker.pb.net.Net.NetMsg, org.chainmaker.pb.net.Net.NetMsg.Builder, org.chainmaker.pb.net.Net.NetMsgOrBuilder> 
          getMsgFieldBuilder() {
        if (msgBuilder_ == null) {
          msgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.chainmaker.pb.net.Net.NetMsg, org.chainmaker.pb.net.Net.NetMsg.Builder, org.chainmaker.pb.net.Net.NetMsgOrBuilder>(
                  getMsg(),
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        return msgBuilder_;
      }

      private java.lang.Object chainId_ = "";
      /**
       * <code>string chain_id = 2;</code>
       * @return The chainId.
       */
      public java.lang.String getChainId() {
        java.lang.Object ref = chainId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          chainId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string chain_id = 2;</code>
       * @return The bytes for chainId.
       */
      public com.google.protobuf.ByteString
          getChainIdBytes() {
        java.lang.Object ref = chainId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          chainId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string chain_id = 2;</code>
       * @param value The chainId to set.
       * @return This builder for chaining.
       */
      public Builder setChainId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        chainId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string chain_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearChainId() {
        
        chainId_ = getDefaultInstance().getChainId();
        onChanged();
        return this;
      }
      /**
       * <code>string chain_id = 2;</code>
       * @param value The bytes for chainId to set.
       * @return This builder for chaining.
       */
      public Builder setChainIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        chainId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object flag_ = "";
      /**
       * <pre>
       * 属于那个模块，判断消息类型
       * </pre>
       *
       * <code>string flag = 3;</code>
       * @return The flag.
       */
      public java.lang.String getFlag() {
        java.lang.Object ref = flag_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          flag_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 属于那个模块，判断消息类型
       * </pre>
       *
       * <code>string flag = 3;</code>
       * @return The bytes for flag.
       */
      public com.google.protobuf.ByteString
          getFlagBytes() {
        java.lang.Object ref = flag_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          flag_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 属于那个模块，判断消息类型
       * </pre>
       *
       * <code>string flag = 3;</code>
       * @param value The flag to set.
       * @return This builder for chaining.
       */
      public Builder setFlag(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        flag_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 属于那个模块，判断消息类型
       * </pre>
       *
       * <code>string flag = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFlag() {
        
        flag_ = getDefaultInstance().getFlag();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 属于那个模块，判断消息类型
       * </pre>
       *
       * <code>string flag = 3;</code>
       * @param value The bytes for flag to set.
       * @return This builder for chaining.
       */
      public Builder setFlagBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        flag_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:net.Msg)
    }

    // @@protoc_insertion_point(class_scope:net.Msg)
    private static final org.chainmaker.pb.net.Net.Msg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.chainmaker.pb.net.Net.Msg();
    }

    public static org.chainmaker.pb.net.Net.Msg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Msg>
        PARSER = new com.google.protobuf.AbstractParser<Msg>() {
      @java.lang.Override
      public Msg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Msg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Msg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Msg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.chainmaker.pb.net.Net.Msg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NetMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.NetMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * payload of the message
     * </pre>
     *
     * <code>bytes payload = 1;</code>
     * @return The payload.
     */
    com.google.protobuf.ByteString getPayload();

    /**
     * <pre>
     * message type
     * </pre>
     *
     * <code>.net.NetMsg.MsgType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <pre>
     * message type
     * </pre>
     *
     * <code>.net.NetMsg.MsgType type = 2;</code>
     * @return The type.
     */
    org.chainmaker.pb.net.Net.NetMsg.MsgType getType();

    /**
     * <pre>
     * nodeId
     * </pre>
     *
     * <code>string to = 3;</code>
     * @return The to.
     */
    java.lang.String getTo();
    /**
     * <pre>
     * nodeId
     * </pre>
     *
     * <code>string to = 3;</code>
     * @return The bytes for to.
     */
    com.google.protobuf.ByteString
        getToBytes();
  }
  /**
   * <pre>
   * net message
   * </pre>
   *
   * Protobuf type {@code net.NetMsg}
   */
  public static final class NetMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:net.NetMsg)
      NetMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NetMsg.newBuilder() to construct.
    private NetMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NetMsg() {
      payload_ = com.google.protobuf.ByteString.EMPTY;
      type_ = 0;
      to_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NetMsg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NetMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              payload_ = input.readBytes();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              to_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.chainmaker.pb.net.Net.internal_static_net_NetMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.chainmaker.pb.net.Net.internal_static_net_NetMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.chainmaker.pb.net.Net.NetMsg.class, org.chainmaker.pb.net.Net.NetMsg.Builder.class);
    }

    /**
     * <pre>
     * specific net message types
     * </pre>
     *
     * Protobuf enum {@code net.NetMsg.MsgType}
     */
    public enum MsgType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>INVALID_MSG = 0;</code>
       */
      INVALID_MSG(0),
      /**
       * <code>TX = 1;</code>
       */
      TX(1),
      /**
       * <code>TXS = 2;</code>
       */
      TXS(2),
      /**
       * <code>BLOCK = 3;</code>
       */
      BLOCK(3),
      /**
       * <code>BLOCKS = 4;</code>
       */
      BLOCKS(4),
      /**
       * <code>CONSENSUS_MSG = 5;</code>
       */
      CONSENSUS_MSG(5),
      /**
       * <code>SYNC_BLOCK_MSG = 6;</code>
       */
      SYNC_BLOCK_MSG(6),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>INVALID_MSG = 0;</code>
       */
      public static final int INVALID_MSG_VALUE = 0;
      /**
       * <code>TX = 1;</code>
       */
      public static final int TX_VALUE = 1;
      /**
       * <code>TXS = 2;</code>
       */
      public static final int TXS_VALUE = 2;
      /**
       * <code>BLOCK = 3;</code>
       */
      public static final int BLOCK_VALUE = 3;
      /**
       * <code>BLOCKS = 4;</code>
       */
      public static final int BLOCKS_VALUE = 4;
      /**
       * <code>CONSENSUS_MSG = 5;</code>
       */
      public static final int CONSENSUS_MSG_VALUE = 5;
      /**
       * <code>SYNC_BLOCK_MSG = 6;</code>
       */
      public static final int SYNC_BLOCK_MSG_VALUE = 6;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MsgType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static MsgType forNumber(int value) {
        switch (value) {
          case 0: return INVALID_MSG;
          case 1: return TX;
          case 2: return TXS;
          case 3: return BLOCK;
          case 4: return BLOCKS;
          case 5: return CONSENSUS_MSG;
          case 6: return SYNC_BLOCK_MSG;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MsgType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
              public MsgType findValueByNumber(int number) {
                return MsgType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.chainmaker.pb.net.Net.NetMsg.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgType[] VALUES = values();

      public static MsgType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MsgType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:net.NetMsg.MsgType)
    }

    public static final int PAYLOAD_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString payload_;
    /**
     * <pre>
     * payload of the message
     * </pre>
     *
     * <code>bytes payload = 1;</code>
     * @return The payload.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <pre>
     * message type
     * </pre>
     *
     * <code>.net.NetMsg.MsgType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * message type
     * </pre>
     *
     * <code>.net.NetMsg.MsgType type = 2;</code>
     * @return The type.
     */
    @java.lang.Override public org.chainmaker.pb.net.Net.NetMsg.MsgType getType() {
      @SuppressWarnings("deprecation")
      org.chainmaker.pb.net.Net.NetMsg.MsgType result = org.chainmaker.pb.net.Net.NetMsg.MsgType.valueOf(type_);
      return result == null ? org.chainmaker.pb.net.Net.NetMsg.MsgType.UNRECOGNIZED : result;
    }

    public static final int TO_FIELD_NUMBER = 3;
    private volatile java.lang.Object to_;
    /**
     * <pre>
     * nodeId
     * </pre>
     *
     * <code>string to = 3;</code>
     * @return The to.
     */
    @java.lang.Override
    public java.lang.String getTo() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        to_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * nodeId
     * </pre>
     *
     * <code>string to = 3;</code>
     * @return The bytes for to.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getToBytes() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        to_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!payload_.isEmpty()) {
        output.writeBytes(1, payload_);
      }
      if (type_ != org.chainmaker.pb.net.Net.NetMsg.MsgType.INVALID_MSG.getNumber()) {
        output.writeEnum(2, type_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(to_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, to_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!payload_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, payload_);
      }
      if (type_ != org.chainmaker.pb.net.Net.NetMsg.MsgType.INVALID_MSG.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(to_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, to_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.chainmaker.pb.net.Net.NetMsg)) {
        return super.equals(obj);
      }
      org.chainmaker.pb.net.Net.NetMsg other = (org.chainmaker.pb.net.Net.NetMsg) obj;

      if (!getPayload()
          .equals(other.getPayload())) return false;
      if (type_ != other.type_) return false;
      if (!getTo()
          .equals(other.getTo())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayload().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + TO_FIELD_NUMBER;
      hash = (53 * hash) + getTo().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.chainmaker.pb.net.Net.NetMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.chainmaker.pb.net.Net.NetMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.chainmaker.pb.net.Net.NetMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.chainmaker.pb.net.Net.NetMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.chainmaker.pb.net.Net.NetMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.chainmaker.pb.net.Net.NetMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.chainmaker.pb.net.Net.NetMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.chainmaker.pb.net.Net.NetMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.chainmaker.pb.net.Net.NetMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.chainmaker.pb.net.Net.NetMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.chainmaker.pb.net.Net.NetMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.chainmaker.pb.net.Net.NetMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.chainmaker.pb.net.Net.NetMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * net message
     * </pre>
     *
     * Protobuf type {@code net.NetMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:net.NetMsg)
        org.chainmaker.pb.net.Net.NetMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.chainmaker.pb.net.Net.internal_static_net_NetMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.chainmaker.pb.net.Net.internal_static_net_NetMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.chainmaker.pb.net.Net.NetMsg.class, org.chainmaker.pb.net.Net.NetMsg.Builder.class);
      }

      // Construct using org.chainmaker.pb.net.Net.NetMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        payload_ = com.google.protobuf.ByteString.EMPTY;

        type_ = 0;

        to_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.chainmaker.pb.net.Net.internal_static_net_NetMsg_descriptor;
      }

      @java.lang.Override
      public org.chainmaker.pb.net.Net.NetMsg getDefaultInstanceForType() {
        return org.chainmaker.pb.net.Net.NetMsg.getDefaultInstance();
      }

      @java.lang.Override
      public org.chainmaker.pb.net.Net.NetMsg build() {
        org.chainmaker.pb.net.Net.NetMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.chainmaker.pb.net.Net.NetMsg buildPartial() {
        org.chainmaker.pb.net.Net.NetMsg result = new org.chainmaker.pb.net.Net.NetMsg(this);
        result.payload_ = payload_;
        result.type_ = type_;
        result.to_ = to_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.chainmaker.pb.net.Net.NetMsg) {
          return mergeFrom((org.chainmaker.pb.net.Net.NetMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.chainmaker.pb.net.Net.NetMsg other) {
        if (other == org.chainmaker.pb.net.Net.NetMsg.getDefaultInstance()) return this;
        if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
          setPayload(other.getPayload());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getTo().isEmpty()) {
          to_ = other.to_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.chainmaker.pb.net.Net.NetMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.chainmaker.pb.net.Net.NetMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * payload of the message
       * </pre>
       *
       * <code>bytes payload = 1;</code>
       * @return The payload.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <pre>
       * payload of the message
       * </pre>
       *
       * <code>bytes payload = 1;</code>
       * @param value The payload to set.
       * @return This builder for chaining.
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * payload of the message
       * </pre>
       *
       * <code>bytes payload = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPayload() {
        
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       * message type
       * </pre>
       *
       * <code>.net.NetMsg.MsgType type = 2;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       * message type
       * </pre>
       *
       * <code>.net.NetMsg.MsgType type = 2;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * message type
       * </pre>
       *
       * <code>.net.NetMsg.MsgType type = 2;</code>
       * @return The type.
       */
      @java.lang.Override
      public org.chainmaker.pb.net.Net.NetMsg.MsgType getType() {
        @SuppressWarnings("deprecation")
        org.chainmaker.pb.net.Net.NetMsg.MsgType result = org.chainmaker.pb.net.Net.NetMsg.MsgType.valueOf(type_);
        return result == null ? org.chainmaker.pb.net.Net.NetMsg.MsgType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * message type
       * </pre>
       *
       * <code>.net.NetMsg.MsgType type = 2;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(org.chainmaker.pb.net.Net.NetMsg.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * message type
       * </pre>
       *
       * <code>.net.NetMsg.MsgType type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object to_ = "";
      /**
       * <pre>
       * nodeId
       * </pre>
       *
       * <code>string to = 3;</code>
       * @return The to.
       */
      public java.lang.String getTo() {
        java.lang.Object ref = to_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          to_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * nodeId
       * </pre>
       *
       * <code>string to = 3;</code>
       * @return The bytes for to.
       */
      public com.google.protobuf.ByteString
          getToBytes() {
        java.lang.Object ref = to_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          to_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * nodeId
       * </pre>
       *
       * <code>string to = 3;</code>
       * @param value The to to set.
       * @return This builder for chaining.
       */
      public Builder setTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        to_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * nodeId
       * </pre>
       *
       * <code>string to = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTo() {
        
        to_ = getDefaultInstance().getTo();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * nodeId
       * </pre>
       *
       * <code>string to = 3;</code>
       * @param value The bytes for to to set.
       * @return This builder for chaining.
       */
      public Builder setToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        to_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:net.NetMsg)
    }

    // @@protoc_insertion_point(class_scope:net.NetMsg)
    private static final org.chainmaker.pb.net.Net.NetMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.chainmaker.pb.net.Net.NetMsg();
    }

    public static org.chainmaker.pb.net.Net.NetMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NetMsg>
        PARSER = new com.google.protobuf.AbstractParser<NetMsg>() {
      @java.lang.Override
      public NetMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NetMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NetMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NetMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.chainmaker.pb.net.Net.NetMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_Msg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_Msg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_NetMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_NetMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rnet/net.proto\022\003net\"?\n\003Msg\022\030\n\003msg\030\001 \001(\013" +
      "2\013.net.NetMsg\022\020\n\010chain_id\030\002 \001(\t\022\014\n\004flag\030" +
      "\003 \001(\t\"\263\001\n\006NetMsg\022\017\n\007payload\030\001 \001(\014\022!\n\004typ" +
      "e\030\002 \001(\0162\023.net.NetMsg.MsgType\022\n\n\002to\030\003 \001(\t" +
      "\"i\n\007MsgType\022\017\n\013INVALID_MSG\020\000\022\006\n\002TX\020\001\022\007\n\003" +
      "TXS\020\002\022\t\n\005BLOCK\020\003\022\n\n\006BLOCKS\020\004\022\021\n\rCONSENSU" +
      "S_MSG\020\005\022\022\n\016SYNC_BLOCK_MSG\020\006B?\n\025org.chain" +
      "maker.pb.netZ&chainmaker.org/chainmaker/" +
      "pb-go/v2/netb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_net_Msg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_net_Msg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_Msg_descriptor,
        new java.lang.String[] { "Msg", "ChainId", "Flag", });
    internal_static_net_NetMsg_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_net_NetMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_NetMsg_descriptor,
        new java.lang.String[] { "Payload", "Type", "To", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
